/**
 * Printing a bitmap on the thermal printer.  ARCHITECTURE.md §2 — pure, no I/O.
 *
 * ── Why this exists at all ──────────────────────────────────────────────────
 *
 * `pplbFidelity()` used to REFUSE any label carrying certification artwork, on
 * the reasoning that "a PPLB thermal stream cannot draw" it, and pushed those
 * labels through a browser popup instead. The premise was half right: PPLB
 * cannot draw an SVG. It does not have to. PPLB is Argox's EPL2-compatible
 * mode, and EPL2 has had a graphics command since forever — you hand it a
 * 1-bit bitmap.
 *
 * The likely origin of the caution is a real note in `lib/production/label-pplb.ts`
 * that "a downloaded Arial was silently dropped". That is the soft-FONT download
 * path, which is a different command and genuinely unreliable on these units. It
 * does not generalise to graphics, and treating it as if it did cost every
 * organic, JAS, Rainforest and Fairtrade label a browser popup at the one moment
 * an operator has a bag in their hands.
 *
 * ── The command ─────────────────────────────────────────────────────────────
 *
 *     GW p1,p2,p3,p4,<binary>
 *
 *     p1  x origin, dots        p3  WIDTH IN BYTES, not dots
 *     p2  y origin, dots        p4  height in dots
 *
 * Two things about the payload that are easy to get backwards, and both print
 * something plausible-looking when wrong:
 *
 *   - It is INVERTED. A 0 bit burns a dot; a 1 bit leaves the label blank. Get
 *     this the wrong way round and every mark prints as a black square with the
 *     artwork knocked out of it — which also holds the head at full power across
 *     the whole cell.
 *   - Rows pad to a byte boundary. Pad with 1s (white). Padding with 0s adds a
 *     black bar down the right-hand edge of every mark.
 *
 * Both are asserted in bitmap.test.ts against the real generated artwork rather
 * than a synthetic fixture, because a fixture would have been built by the same
 * hand that wrote the packer and would agree with it whether or not it is right.
 *
 * ── What is NOT settled here ────────────────────────────────────────────────
 *
 * Bit polarity is stated by the EPL2 specification, and the generator and this
 * module agree with each other — but agreeing with each other is not the same
 * as agreeing with the printer. NOTHING HERE HAS BEEN PUT ON PAPER YET. Print
 * one mark on a real CP-2140EX before this goes near a customer bag; if it
 * comes out inverted, `INVERT_BITS` below is the single place to flip.
 */

/** One piece of artwork, rasterised for the printer. */
export interface MarkBitmap {
  key: string
  /** Artwork filename it was generated from, so a mismatch is traceable. */
  source: string
  widthDots: number
  heightDots: number
  /** Row stride. EPL2 takes the width in BYTES, which is why this is stored. */
  widthBytes: number
  /** Packed rows, base64. MSB-first, one bit per dot. */
  dataBase64: string
}

/**
 * EPL2 says a 0 bit prints black. Kept as a named constant rather than inlined
 * so that if a test print comes out inverted, the fix is one line here and not
 * a hunt through a packer written in Python and a decoder written in
 * TypeScript.
 */
export const INVERT_BITS = true

export interface BitmapPlacement {
  /** Dots from the left edge of the label. */
  x: number
  /** Dots from the top edge. */
  y: number
}

function decodeBase64(b64: string): Uint8Array {
  // atob exists in the browser and in Node 16+; Buffer only in Node. Core must
  // run in both (the editor previews, the print route emits), so prefer the
  // standard one and fall back rather than importing anything.
  if (typeof atob === 'function') {
    const bin = atob(b64)
    const out = new Uint8Array(bin.length)
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i)
    return out
  }
  /* c8 ignore next 2 — Node <16 only */
  const B = (globalThis as { Buffer?: { from(s: string, e: string): Uint8Array } }).Buffer
  if (B) return B.from(b64, 'base64')
  throw new Error('no base64 decoder available')
}

/**
 * Unpack to rows of booleans, `true` meaning a dot is burned.
 *
 * Exported because it is what makes the packing testable and previewable — the
 * generated bytes can be turned back into a picture and compared with the
 * artwork, which is the only way to catch an inversion or a stride error
 * without a printer.
 */
export function bitmapToRows(bm: MarkBitmap): boolean[][] {
  const bytes = decodeBase64(bm.dataBase64)
  const expected = bm.widthBytes * bm.heightDots
  if (bytes.length !== expected) {
    throw new Error(
      `${bm.key}: payload is ${bytes.length} bytes, expected ${expected} ` +
      `(${bm.widthBytes} bytes/row x ${bm.heightDots} rows)`,
    )
  }
  const rows: boolean[][] = []
  for (let y = 0; y < bm.heightDots; y++) {
    const row: boolean[] = []
    for (let x = 0; x < bm.widthDots; x++) {
      const byte = bytes[y * bm.widthBytes + (x >> 3)]
      const bit = (byte & (0x80 >> (x & 7))) !== 0
      row.push(INVERT_BITS ? !bit : bit)
    }
    rows.push(row)
  }
  return rows
}

/**
 * The `GW` command for one bitmap, as a latin1 string.
 *
 * Latin1 and not UTF-8: the payload is raw bytes, and any byte above 0x7F
 * would become two bytes under UTF-8 — the printer would read a stride that no
 * longer matches `widthBytes` and produce a sheared image. Whatever writes this
 * to the socket must use the same encoding.
 */
export function markToPplb(bm: MarkBitmap, at: BitmapPlacement): string {
  if (!Number.isInteger(at.x) || !Number.isInteger(at.y) || at.x < 0 || at.y < 0) {
    throw new Error(`${bm.key}: placement must be non-negative integers, got ${at.x},${at.y}`)
  }
  const bytes = decodeBase64(bm.dataBase64)
  let payload = ''
  for (let i = 0; i < bytes.length; i++) payload += String.fromCharCode(bytes[i])
  return `GW${at.x},${at.y},${bm.widthBytes},${bm.heightDots},${payload}\r\n`
}

/**
 * Lay marks out in a row, centred on `centreX`, and return the commands.
 *
 * Centred rather than left-aligned because the number of marks varies by
 * template — one for a plain export label, four for Kunitaro RA organic — and a
 * left-aligned strip drifts off-centre as marks are added, which looks like a
 * printing fault rather than a layout choice.
 */
export function markStripToPplb(
  marks: readonly MarkBitmap[],
  opts: { centreX: number; y: number; gapDots?: number },
): string {
  if (marks.length === 0) return ''
  const gap = opts.gapDots ?? 8
  const total = marks.reduce((a, m) => a + m.widthDots, 0) + gap * (marks.length - 1)
  let x = Math.round(opts.centreX - total / 2)
  if (x < 0) x = 0
  let out = ''
  for (const m of marks) {
    out += markToPplb(m, { x, y: opts.y })
    x += m.widthDots + gap
  }
  return out
}
