import { describe, it, expect } from 'vitest'
import { bitmapToRows, markToPplb } from '@/lib/core/labels/bitmap'
import { MARK_BITMAPS } from './mark-bitmaps.generated'

/**
 * The REAL certification artwork.
 *
 * Nothing here has been on paper yet, so these cannot prove the printer agrees.
 * What they can prove is that the generated bytes are self-consistent and not
 * inverted — the two failure modes that print something plausible-looking and
 * wrong, which on a certification mark is a bag that cannot be sold rather than
 * a cosmetic defect.
 *
 * The generator is Python and the decoder is TypeScript, written from the same
 * EPL2 reading. These assertions are deliberately about PROPERTIES of the
 * artwork — corners blank, coverage in a sane band, dimensions matching the
 * payload — and not "the bytes equal this literal", because a golden-bytes test
 * would agree with the packer whether or not the packer is right.
 */

const KEYS = ['jas', 'control_union', 'rainforest_alliance', 'fairtrade', 'cape_natural'] as const

describe('every certification mark is present', () => {
  it.each(KEYS)('%s', key => {
    expect(MARK_BITMAPS[key], `${key} missing — rerun scripts/build-mark-bitmaps.py`).toBeDefined()
  })

  it('has no extra marks the label model does not know about', () => {
    expect(Object.keys(MARK_BITMAPS).sort()).toEqual([...KEYS].sort())
  })
})

describe('each bitmap is internally consistent', () => {
  it.each(KEYS)('%s', key => {
    const bm = MARK_BITMAPS[key]
    expect(bm.widthBytes).toBe(Math.ceil(bm.widthDots / 8))
    // Throws if the payload length disagrees with the stated dimensions.
    const rows = bitmapToRows(bm)
    expect(rows).toHaveLength(bm.heightDots)
    expect(rows[0]).toHaveLength(bm.widthDots)
  })
})

describe('the artwork is not inverted', () => {
  /**
   * Every mark is centred on a white square, so all four corners must be blank.
   * If polarity were flipped, all four would be burned — and the mark would
   * print as a black tile with the artwork knocked out of it.
   */
  it.each(KEYS)('%s has blank corners', key => {
    const rows = bitmapToRows(MARK_BITMAPS[key])
    const h = rows.length, w = rows[0].length
    expect(rows[0][0], 'top-left').toBe(false)
    expect(rows[0][w - 1], 'top-right').toBe(false)
    expect(rows[h - 1][0], 'bottom-left').toBe(false)
    expect(rows[h - 1][w - 1], 'bottom-right').toBe(false)
  })

  it.each(KEYS)('%s has plausible ink coverage', key => {
    const rows = bitmapToRows(MARK_BITMAPS[key])
    const total = rows.length * rows[0].length
    const black = rows.reduce((a, r) => a + r.filter(Boolean).length, 0)
    const pct = (black / total) * 100
    // An all-white or all-black cell is the signature of a broken conversion.
    // Fairtrade is a solid black panel and sits near 50%; the rest are line art
    // at 15-30%. The band is wide on purpose — this catches catastrophe, not
    // artistic variation.
    expect(pct, `${key} coverage ${pct.toFixed(1)}%`).toBeGreaterThan(5)
    expect(pct, `${key} coverage ${pct.toFixed(1)}%`).toBeLessThan(70)
  })
})

describe('each mark renders to a GW command the printer can parse', () => {
  it.each(KEYS)('%s', key => {
    const bm = MARK_BITMAPS[key]
    const out = markToPplb(bm, { x: 16, y: 260 })
    expect(out.startsWith(`GW16,260,${bm.widthBytes},${bm.heightDots},`)).toBe(true)
    const header = `GW16,260,${bm.widthBytes},${bm.heightDots},`
    expect(out.length).toBe(header.length + bm.widthBytes * bm.heightDots + 2)
  })
})

describe('the marks fit the label', () => {
  /**
   * Argox CP-2140EX at 203dpi, 100mm x 49.2mm landscape = 800 x 394 dots — the
   * same geometry lib/production/label-pplb.ts already prints bag tags on.
   *
   * Four marks is the worst case in the template set (Kunitaro RA organic).
   */
  const LABEL_W = 800
  const LABEL_H = 394
  const MARGIN = 16          // the printer's own unprintable edge, both sides

  it('four marks and their gaps fit the label width', () => {
    const four = [MARK_BITMAPS.jas, MARK_BITMAPS.control_union,
                  MARK_BITMAPS.rainforest_alliance, MARK_BITMAPS.fairtrade]
    const total = four.reduce((a, m) => a + m.widthDots, 0) + 8 * 3
    // 4 x 96 + 3 x 8 = 408 of 800. Comfortable across, and NOT the binding
    // constraint — see the height test below, which is.
    expect(total).toBeLessThanOrEqual(LABEL_W - MARGIN * 2)
  })

  it('leaves enough height for the densest template, and says what that costs', () => {
    /**
     * THE REAL CONSTRAINT, and it is tighter than the width.
     *
     * A 96-dot mark strip takes a quarter of a 394-dot label. What is left for
     * text is 394 - 96 - padding, and the template set runs from 8 lines to 16.
     * At the printer's font 3 (20 dots) sixteen lines need 320 dots, which does
     * NOT fit alongside the strip — those templates must drop to a smaller
     * font, and render.test.ts already asserts the fit per template because a
     * silently truncated line ("Manufacturer: Cape Natural Tea Pr...") is how
     * this bit the project once already.
     *
     * Recorded as a test rather than a comment so that shrinking the label or
     * growing the marks fails here instead of on a bag.
     */
    const strip = MARK_BITMAPS.jas.heightDots
    const padding = 16
    const forText = LABEL_H - strip - padding
    expect(forText).toBeGreaterThanOrEqual(240)   // 12 lines at font 3
    expect(strip / LABEL_H).toBeLessThan(0.3)     // marks stay a quarter, not a third
  })

  it('no mark is taller than the label', () => {
    for (const key of KEYS) expect(MARK_BITMAPS[key].heightDots).toBeLessThan(LABEL_H)
  })
})
