-- EU MRL reference data, continuously synced from the official EU Pesticides
-- Database bulk MRL export. Residue grading (R-0..R-3) resolves each detected
-- compound's Maximum Residue Level from this table (by normalised pesticide
-- name + commodity) so grades track the current EU limits instead of relying
-- solely on the value printed on each lab report.

CREATE TABLE IF NOT EXISTS qms.eu_mrl (
  id             bigint generated by default as identity primary key,
  pesticide      text not null,               -- active substance, as the EU spells it
  pesticide_norm text not null,               -- normalised key for lookups
  commodity_code text not null,               -- EU product code (Rooibos = 0632020)
  commodity      text,                         -- human label, e.g. 'Rooibos'
  mrl_mg_kg      numeric,                      -- parsed numeric MRL in mg/kg
  mrl_raw        text,                         -- original cell text (may carry * / footnotes)
  source         text not null default 'eu_pesticides_db',
  synced_at      timestamptz not null default now(),
  CONSTRAINT eu_mrl_uniq UNIQUE (pesticide_norm, commodity_code)
);
CREATE INDEX IF NOT EXISTS eu_mrl_lookup_idx ON qms.eu_mrl (commodity_code, pesticide_norm);

-- One row per sync run, so the UI / operators can see when it last ran and how it went.
CREATE TABLE IF NOT EXISTS qms.eu_mrl_sync_log (
  id            bigint generated by default as identity primary key,
  started_at    timestamptz not null default now(),
  finished_at   timestamptz,
  status        text not null default 'running',  -- running | success | error
  rows_upserted int,
  commodity     text,
  triggered_by  text,                              -- user handle or 'cron'
  message       text
);
CREATE INDEX IF NOT EXISTS eu_mrl_sync_log_at_idx ON qms.eu_mrl_sync_log (started_at desc);

GRANT SELECT ON qms.eu_mrl               TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON qms.eu_mrl               TO authenticated, service_role;
GRANT SELECT ON qms.eu_mrl_sync_log      TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON qms.eu_mrl_sync_log      TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE qms.eu_mrl_id_seq          TO authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE qms.eu_mrl_sync_log_id_seq TO authenticated, service_role;
