-- ============================================================
-- CNTP Production Capture - Master inventory (from Acumatica IN-StockItem export)
-- Run in: Supabase SQL Editor (staging first, then production)
-- 630 items. Re-runnable (upsert).
-- ============================================================

CREATE TABLE IF NOT EXISTS production.inventory_items (
  inventory_id   text PRIMARY KEY,
  description    text,
  item_class     text,
  category_code  text,
  product_group  text,
  grade          text,
  qc_grade       text,
  variant        text,
  base_unit      text,
  item_status    text,
  active         boolean NOT NULL DEFAULT true,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inventory_items_class_idx   ON production.inventory_items(item_class);
CREATE INDEX IF NOT EXISTS inventory_items_variant_idx ON production.inventory_items(variant);
CREATE INDEX IF NOT EXISTS inventory_items_group_idx   ON production.inventory_items(product_group);

GRANT USAGE ON SCHEMA production TO authenticated, service_role;
GRANT ALL ON production.inventory_items TO authenticated, service_role;
ALTER TABLE production.inventory_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS auth_all_inventory_items ON production.inventory_items;
CREATE POLICY auth_all_inventory_items ON production.inventory_items FOR ALL TO authenticated USING (true) WITH CHECK (true);

INSERT INTO production.inventory_items
  (inventory_id, description, item_class, category_code, product_group, grade, qc_grade, variant, base_unit, item_status)
VALUES
('05RMDBL-C','Raw Material Dry: Export Blend Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Export Blend','Conventional','KG','No Sales'),
('05RMDBL-O','Raw Material Dry: Export Blend Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Export Blend','Organic','KG','No Sales'),
('05RMDBL-RC','Raw Material Dry: Export Blend RA-Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Export Blend','RA-Conventional','KG','No Sales'),
('05RMDBL-RO','Raw Material Dry: Export Blend RA-Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Export Blend','RA-Organic','KG','No Sales'),
('05RMDD-C','Raw Material Dry: Domestic Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Domestic','Conventional','KG','No Sales'),
('05RMDD-O','Raw Material Dry: Domestic Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Domestic','Organic','KG','No Sales'),
('05RMDD-RC','Raw Material Dry: Domestic RA-Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Domestic','RA-Conventional','KG','No Sales'),
('05RMDD-RO','Raw Material Dry: Domestic RA-Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Domestic','RA-Organic','KG','No Sales'),
('05RMDE-C','Raw Material Dry: Export Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Export','Conventional','KG','No Sales'),
('05RMDE-O','Raw Material Dry: Export Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Export','Organic','KG','No Sales'),
('05RMDE-RC','Raw Material Dry: Export RA-Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Export','RA-Conventional','KG','No Sales'),
('05RMDE-RO','Raw Material Dry: Export RA-Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Export','RA-Organic','KG','No Sales'),
('05RMDLC-C','Raw Mateiral Dry: Long Cut Conventional','05RAWMDRY','Rooibos','Raw Dry','Other',null,'Conventional','KG','No Sales'),
('05RMDLC-O','Raw Mateiral Dry: Long Cut Organic','05RAWMDRY','Rooibos','Raw Dry','Other',null,'Organic','KG','No Sales'),
('05RMWG-C','Raw Material Wet: Green Conventional','05RAWMWET','Rooibos','Raw Wet','Other',null,'Conventional','KG','No Sales'),
('05RMWG-O','Raw Material Wet: Green Organic','05RAWMWET','Rooibos','Raw Wet','Other',null,'Organic','KG','No Sales'),
('05RMDCON-C','Raw Material Dry: Consignment Conventional','05RAWMDRY','Rooibos','Raw Dry','Other',null,'Conventional','KG','No Sales'),
('05RMDCON-O','Raw Material Dry: Consignment Organic','05RAWMDRY','Rooibos','Raw Dry','Other',null,'Organic','KG','No Sales'),
('05RMDB-C','Whole Rosehip Berries - Dry Conventional','05RAWMDRY','Rosehip','Raw Dry','Other',null,'Conventional','KG','No Sales'),
('05RMDB-O','Whole Rosehip Berries - Dry Organic','05RAWMDRY','Rosehip','Raw Dry','Other',null,'Organic','KG','No Sales'),
('05RMWB-C','Whole Rosehip Berries - Wet Conventional','05RAWMWET','Rosehip','Raw Wet','Other',null,'Conventional','KG','No Sales'),
('05RMWB-O','Whole Rosehip Berries - Wet Organic','05RAWMWET','Rosehip','Raw Wet','Other',null,'Organic','KG','No Sales'),
('01CP-RMD-C','Contract Processing: Raw Material Dry - Conventional','01CPRAWMDR','Rooibos','Raw Dry','Other',null,'Conventional','KG','No Purchases'),
('01CP-RMG-C','Contract Processing: Raw Material Wet Green - Conventional','01CPRAWMWE','Rooibos','Raw Wet','Other',null,'Conventional','KG','No Sales'),
('01CP-RMD-O','Contract Processing: Raw Material Dry - Organic','01CPRAWMDR','Rooibos','Raw Wet','Other',null,'Conventional','KG','No Purchases'),
('01CP-RMG-O','Contract Processing: Raw Material Wet Green - Organic','01CPRAWMWE','Rooibos','Raw Wet','Other',null,'Conventional','KG','No Sales'),
('15IGALT-C','ALT - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGALT-O','ALT - Organic','15GRINTDST','Rooibos','Dust','Other',null,'Organic','KG','No Sales'),
('15IGCP-ALT','Contract Processing: ALT','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGCP-DB','Contract Processing: Dust - Brown','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGCPDG','Contract Processing Dust Green','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDALT-C','Dust: ALT - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDALT-O','Dust: ALT - Organic','15GRINTDST','Rooibos','Dust','Other',null,'Organic','KG','No Sales'),
('15IGDB-C','Dust: Brown  - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDBC-C','Dust: Brown ( Coarse ) - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDBC-O','Dust: Brown ( Coarse ) - Organic','15GRINTDST','Rooibos','Dust','Other',null,'Organic','KG','No Sales'),
('15IGDB-O','Dust: Brown  - Organic','15GRINTDST','Rooibos','Dust','Other',null,'Organic','KG','No Sales'),
('15IGDB-RC','Dust: Brown  - RA Conventional','15GRINTDST','Rooibos','Dust','Other',null,'RA-Conventional','KG','No Sales'),
('15IGDB-RO','Dust: Brown  - RA Organic','15GRINTDST','Rooibos','Dust','Other',null,'RA-Organic','KG','No Sales'),
('15IGDIS-C','Dust: Indent - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDISC-C','Dust: IS (Coarse) - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDISC-O','Dust: IS (Coarse) - Organic','15GRINTDST','Rooibos','Dust','Other',null,'Organic','KG','No Sales'),
('15IGDIS-O','Dust: Indent - Organic','15GRINTDST','Rooibos','Dust','Other',null,'Organic','KG','No Sales'),
('15IGDIS-RC','Dust: Indent - RA Conventional','15GRINTDST','Rooibos','Dust','Other',null,'RA-Conventional','KG','No Sales'),
('15IGDIS-RO','Dust: Indent - RA Organic','15GRINTDST','Rooibos','Dust','Other',null,'RA-Organic','KG','No Sales'),
('15IGDLG-C','Dust: Leaf Grade - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDLG-O','Dust: Leaf Grade - Organic','15GRINTDST','Rooibos','Dust','Other',null,'Organic','KG','No Sales'),
('15IGDSF-C','Dust: SF - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDSF-O','Dust: SF - Organic','15GRINTDST','Rooibos','Dust','Other',null,'Organic','KG','No Sales'),
('15IGDSF-RC','Dust: SF - RA Conventional','15GRINTDST','Rooibos','Dust','Other',null,'RA-Conventional','KG','No Sales'),
('15IGDSF-RO','Dust: SF - RA Organic','15GRINTDST','Rooibos','Dust','Other',null,'RA-Organic','KG','No Sales'),
('15IGDSG-C','Dust: SG - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDSG-O','Dust: SG - Organic','15GRINTDST','Rooibos','Dust','Other',null,'Organic','KG','No Sales'),
('15IGDSG-RC','Dust: SG - RA Conventional','15GRINTDST','Rooibos','Dust','Other',null,'RA-Conventional','KG','No Sales'),
('15IGDSG-RO','Dust: SG - RA Organic','15GRINTDST','Rooibos','Dust','Other',null,'RA-Organic','KG','No Sales'),
('15IGDSS-C','Dust: SS - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDW-C','Dust: White - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDWC-C','Dust: White ( Coarse ) - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDW-O','Dust: White - Organic','15GRINTDST','Rooibos','Dust','Other',null,'Organic','KG','No Sales'),
('15IGDW-RC','Dust: White - RA Conventional','15GRINTDST','Rooibos','Dust','Other',null,'RA-Conventional','KG','No Sales'),
('15IGDW-RO','Dust: White - RA Organic','15GRINTDST','Rooibos','Dust','Other',null,'RA-Organic','KG','No Sales'),
('15IGCP-LGC','Contract Processing - Coarse Leaf','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Conventional','KG','No Sales'),
('15IGCP-LGF','Contract Processing - Fine Leaf','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Conventional','KG','No Sales'),
('10LGCCL-C','Cutter Coarse Leaf - Conventional','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Conventional','KG','No Sales'),
('10LGCCL-O','Cutter Coarse Leaf - Organic','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Organic','KG','No Sales'),
('10LGCFL-C','Cutter Fine Leaf - Conventional','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Conventional','KG','No Sales'),
('10LGCFL-O','Cutter Fine Leaf - Organic','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Organic','KG','No Sales'),
('10LGRWC-C','Reworked Coarse Leaf -  Conventional','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Conventional','KG','No Sales'),
('10LGDC-C','Sieved Coarse Leaf Domestic - Conventional','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Conventional','KG','No Sales'),
('10LGDC-O','Sieved Coarse Leaf Domestic - Organic','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Organic','KG','No Sales'),
('10LGDC-RC','Sieved Coarse Leaf Domestic - RA Conventional','10GRLEAF','Rooibos','Leaf','Short Cut',null,'RA-Conventional','KG','No Sales'),
('10LGDC-RO','Sieved Coarse Leaf Domestic - RA Organic','10GRLEAF','Rooibos','Leaf','Short Cut',null,'RA-Organic','KG','No Sales'),
('10LGEC-C','Sieved Coarse Leaf: Export - Conventional','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Conventional','KG','No Sales'),
('10LGEC-O','Sieved Coarse Leaf: Export - Organic','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Organic','KG','Active'),
('10LGEC-RC','Sieved Coarse Leaf: Export - RA Conventional','10GRLEAF','Rooibos','Leaf','Short Cut',null,'RA-Conventional','KG','No Sales'),
('10LGEC-RO','Sieved Coarse Leaf: Export - RA Organic','10GRLEAF','Rooibos','Leaf','Short Cut',null,'RA-Organic','KG','Active'),
('10LGBLC-C','Sieved Coarse Leaf: Export Blend - Conventional','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Conventional','KG','No Sales'),
('10LGBLC-O','Sieved Coarse Leaf: Export Blend - Organic','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Organic','KG','No Sales'),
('10LGBLC-RC','Sieved Coarse Leaf: Export Blend - RA Conventional','10GRLEAF','Rooibos','Leaf','Short Cut',null,'RA-Conventional','KG','No Sales'),
('10LGBLC-RO','Sieved Coarse Leaf: Export Blend - RA Organic','10GRLEAF','Rooibos','Leaf','Short Cut',null,'RA-Organic','KG','No Sales'),
('10LGDF-C','Sieved Fine Leaf Domestic - Conventional','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Conventional','KG','No Sales'),
('10LGDF-O','Sieved Fine Leaf Domestic - Organic','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Organic','KG','No Sales'),
('10LGDF-RC','Sieved Fine Leaf Domestic - RA Conventional','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'RA-Conventional','KG','No Sales'),
('10LGDF-RO','Sieved Fine Leaf Domestic - RA Organic','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'RA-Organic','KG','No Sales'),
('10LGEF-C','Sieved Fine Leaf: Export - Conventional','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Conventional','KG','No Sales'),
('10LGEF-O','Sieved Fine Leaf: Export - Organic','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Organic','KG','No Sales'),
('10LGEF-RC','Sieved Fine Leaf: Export - RA Conventional','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'RA-Conventional','KG','No Sales'),
('10LGEF-RO','Sieved Fine Leaf: Export - RA Organic','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'RA-Organic','KG','No Sales'),
('10LGBLF-C','Sieved Fine Leaf: Export Blend - Conventional','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Conventional','KG','No Sales'),
('10LGBLF-O','Sieved Fine Leaf: Export Blend - Organic','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Organic','KG','No Sales'),
('10LGBLF-RC','Sieved Fine Leaf: Export Blend - RA Conventional','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'RA-Conventional','KG','No Sales'),
('10LGBLF-RO','Sieved Fine Leaf: Export Blend - RA Organic','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'RA-Organic','KG','No Sales'),
('10LGRSRD-C','Sieved Rotex Leaf: Domestic -  Conventional','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Conventional','KG','No Sales'),
('10LGESC-C','Sieved Short Cut Export  - Conventional','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Conventional','KG','No Sales'),
('15IGDUF-C','Dust: Ultra Fine - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('05RMDCON-PEL-C','Consignment Stock: Pelargonium','05RAWMDRY','Botanicals','Raw Dry','Other',null,'Conventional','KG','No Sales'),
('05RMDGREEN-C','Raw Material Dry: Green Conventional','05RAWMDRY','Rooibos','Raw Dry','Other',null,'Conventional','KG','No Sales'),
('05RMDGREEN-O','Raw Material Dry: Green Organic','05RAWMDRY','Rooibos','Raw Dry','Other',null,'Organic','KG','No Sales'),
('05RMDCON-RC','Raw Material Dry: Consignment RA-Conventional','05RAWMDRY','Rooibos','Raw Dry','Other',null,'RA-Conventional','KG','No Sales'),
('05RMDCON-RO','Raw Material Dry: Consignment RA-Organic','05RAWMDRY','Rooibos','Raw Dry','Other',null,'RA-Organic','KG','No Sales'),
('05RMD-REJECT-C','Raw Material Dry: Rejected Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Rejected','Conventional','KG','No Sales'),
('05RMD-REJECT-O','Raw Material Dry: Rejected Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Rejected','Organic','KG','No Sales'),
('05RMD-REJECT-RC','Raw Material Dry: Rejected RA-Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Rejected','RA-Conventional','KG','No Sales'),
('05RMD-REJECT-RO','Raw Material Dry: Rejected RA-Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Rejected','RA-Organic','KG','No Sales'),
('10LGCCL-COL-C','Cutter Coarse Leaf (Coloured) - Conventional','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Conventional','KG','No Sales'),
('10LGCCL-COL-O','Cutter Coarse Leaf (Coloured) - Organic','10GRLEAF','Rooibos','Leaf','Short Cut',null,'Organic','KG','No Sales'),
('10LGCFL-COL-C','Cutter Fine Leaf (Coloured) -  Conventional','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Conventional','KG','No Sales'),
('10LGCFL-COL-O','Cutter Fine Leaf (Coloured) - Organic','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Organic','KG','No Sales'),
('10LG-LCCL-C','Long Cut:  Long Leaf - Conventional','10GRLEAF','Rooibos','Leaf','Long Cut',null,'Conventional','KG','No Sales'),
('10LGORG-LCCL','Long Cut:  Long Leaf - Organic','10GRLEAF','Rooibos','Leaf','Long Cut',null,'Organic','KG','No Sales'),
('10LG-LCFL-C','Long Cut: Short Leaf - Conventional','10GRLEAF','Rooibos','Leaf','Long Cut',null,'Conventional','KG','No Sales'),
('10LG-LCFL-O','Long Cut: Short Leaf - Organic','10GRLEAF','Rooibos','Leaf','Long Cut',null,'Organic','KG','No Sales'),
('10LGEF-PAS-C','Sieved Fine Leaf: Export - Pasteurised Conventional','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Conventional','KG','No Sales'),
('15IGDPOWDR-C','Dust: Powder - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGDPOWDR-O','Dust: Powder - Organic','15GRINTDST','Rooibos','Dust','Other',null,'Organic','KG','No Sales'),
('15IGDPOWDR-RC','Dust: Powder - RA Conventional','15GRINTDST','Rooibos','Dust','Other',null,'RA-Conventional','KG','No Sales'),
('15IGDPOWDR-RO','Dust: Powder - RA Organic','15GRINTDST','Rooibos','Dust','Other',null,'RA-Organic','KG','No Sales'),
('15IGPASTDB-C','Dust: Pasteurised - Conventional','15GRINTDST','Rooibos','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGPASTDB-O','Dust: Pasteurised - Organic','15GRINTDST','Rooibos','Dust','Other',null,'Organic','KG','No Sales'),
('20BGGE-001-C','Granule Export : (67BD|25IS|8POW) - Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'Conventional','KG','No Sales'),
('20BGGE-001-O','Granule Export : (67BD|25IS|8POW) - Organic','20GRBLDGR','Rooibos','Granules','Other',null,'Organic','KG','No Sales'),
('20BGGE-002-C','Granules: Export: (56BD|36IS|8POW) - Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'Conventional','KG','No Sales'),
('20BGGE-002-O','Granules: Export: (56BD|36IS|8POW) - Organic','20GRBLDGR','Rooibos','Granules','Other',null,'Organic','KG','No Sales'),
('20BGGE-002-RC','Granules: Export: (56BD|36IS|8POW) - RA Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'RA-Conventional','KG','No Sales'),
('20BGGE-002-RO','Granules: Export: (56BD|36IS|8POW) - RA Organic','20GRBLDGR','Rooibos','Granules','Other',null,'RA-Organic','KG','No Sales'),
('20BGGF-001-C','Granules: Fine: (67BD|25IS|8POW) - Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'Conventional','KG','No Sales'),
('20BGGF-001-O','Granules: Fine: (67BD|25IS|8POW) - Organic','20GRBLDGR','Rooibos','Granules','Other',null,'Organic','KG','No Sales'),
('20BGGF-001-RC','Granules: Fine: (67BD|25IS|8POW) - RA Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'RA-Conventional','KG','No Sales'),
('20BGGF-001-RO','Granules: Fine: (67BD|25IS|8POW) - RA Organic','20GRBLDGR','Rooibos','Granules','Other',null,'RA-Organic','KG','No Sales'),
('20BGGF-002-C','Granules: Fine: (56BD|36IS|8POW) - Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'Conventional','KG','No Sales'),
('20BGGF-002-O','Granules: Fine: (56BD|36IS|8POW) - Organic','20GRBLDGR','Rooibos','Granules','Other',null,'Organic','KG','No Sales'),
('20BGGF-002-RC','Granules: Fine: (56BD|36IS|8POW) - RA Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'RA-Conventional','KG','No Sales'),
('20BGGF-002-RO','Granules: Fine: (56BD|36IS|8POW) - RA Organic','20GRBLDGR','Rooibos','Granules','Other',null,'RA-Organic','KG','No Sales'),
('20BGGF-003-C','Granules: Fine: (40BD|60IS) - Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'Conventional','KG','No Sales'),
('20BGGF-003-O','Granules: Fine: (40BD|60IS) - Organic','20GRBLDGR','Rooibos','Granules','Other',null,'Organic','KG','No Sales'),
('20BGGF-003-RC','Granules: Fine: (40BD|60IS) - RA Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'RA-Conventional','KG','No Sales'),
('20BGGF-003-RO','Granules: Fine: (40BD|60IS) - RA Organic','20GRBLDGR','Rooibos','Granules','Other',null,'RA-Organic','KG','No Sales'),
('20BGGF-CL-001','Granule Fine Coarse Leaf - Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'Conventional','KG','No Sales'),
('20BGGSG-001-C','Granules SG: (29BD|18WD|45IS|8PWD  ) - Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'Conventional','KG','No Sales'),
('20BGGSG-001-O','Granules SG: (29BD|18WD|45IS|8PWD  ) - Organic','20GRBLDGR','Rooibos','Granules','Other',null,'Organic','KG','No Sales'),
('20BGGSG-001-RC','Granules SG: (29BD|18WD|45IS|8PWD  ) - RA Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'RA-Conventional','KG','No Sales'),
('20BGGSG-001-RO','Granules SG: (29BD|18WD|45IS|8PWD  ) - RA Organic','20GRBLDGR','Rooibos','Granules','Other',null,'RA-Organic','KG','No Sales'),
('20BGGSG-CL-001','Granules SG-Coarse Leaf - Conventional','20GRBLDGR','Rooibos','Granules','Other',null,'Conventional','KG','No Sales'),
('20BGGRHC-C','RH Granules: Coarse - Conventional','20GRBLDGR','Rosehip','Granules','Other',null,'Conventional','KG','No Sales'),
('20BGGRHC-O','RH Granules: Coarse - Organic','20GRBLDGR','Rosehip','Granules','Other',null,'Organic','KG','No Sales'),
('20BGGRHTBC-C','RH Granules: TBC - Conventional','20GRBLDGR','Rosehip','Granules','Other',null,'Conventional','KG','No Sales'),
('20BGGRHTBC-O','RH Granules: TBC - Organic','20GRBLDGR','Rosehip','Granules','Other',null,'Organic','KG','No Sales'),
('20BGRHPEL-C','Rosehip Pellet - Conventional','20GRBLDGR','Rosehip','Granules','Other',null,'Conventional','KG','No Sales'),
('20BGRHPEL-O','Rosehip Pellet - Organic','20GRBLDGR','Rosehip','Granules','Other',null,'Organic','KG','No Sales'),
('25BLDAND-TBC-001-C','Phyto: Dandelion Herb Cut - Conventional','20GRBLDOTH','Botanicals','Blend','Other',null,'Conventional','KG','No Sales'),
('25BLGNGR-TBC-001-C','Phyto: Ginger Tea Cut - Conventional','20GRBLDOTH','Botanicals','Blend','Other',null,'Conventional','KG','No Sales'),
('25BLPHYTO-001-C','Blend: Phyto Blend - Conventional','20GRBLDOTH','Botanicals','Blend','Other',null,'Conventional','KG','No Sales'),
('70FLV-LMN-01-C','Flavouring: Lemon - Conventional','20GRBLDOTH','Flavour','Flavour','Other',null,'Conventional','KG','No Sales'),
('70FLV-ORAN-001-C','Flavouring: Orange - Conventional','20GRBLDOTH','Flavour','Flavour','Other',null,'Conventional','KG','No Sales'),
('25BLHB-TBC-001-C','Phyto: Honey Bush Tea Cut - Conventional','20GRBLDOTH','Botanicals','Blend','Other',null,'Conventional','KG','No Sales'),
('29FPESP-001-LC-C','Blend: Drink: RBOS Espresso - Conventional','20GRBLDOTH','Rooibos','Blend','Other',null,'Conventional','KG','No Sales'),
('29FPESP-002-LC-C','Blend: Drink: RBOS Espresso - Conventional','20GRBLDOTH','Rooibos','Blend','Other',null,'Conventional','KG','No Sales'),
('20BGPYR-C','Blending Grade: Pyramid Cut - Conventional','20GRBLDOTH','Rosehip','Blend','Other',null,'Conventional','KG','No Sales'),
('20BGPYR-O','Blending Grade: Pyramid Cut - Organic','20GRBLDOTH','Rosehip','Blend','Other',null,'Organic','KG','No Sales'),
('20BGTBC-C','Blending Grade: TBC - Conventional','20GRBLDOTH','Rosehip','Blend','Other',null,'Conventional','KG','No Sales'),
('20BGTBC-O','Blending Grade: TBC - Organic','20GRBLDOTH','Rosehip','Blend','Other',null,'Organic','KG','No Sales'),
('20BGTBC-CP-C','Blending Grade: TBC - Contract Processing - Conventional','20GRBLDOTH','Rosehip','Blend','Other',null,'Conventional','KG','No Sales'),
('25BGTBC-CP','Contract Processing: TBC for Blend - Conventional','20GRBLDOTH','Rosehip','Intermed','Other',null,'Conventional','KG','No Sales'),
('25BGTBCS-C','TBC Seed For Blend - Conventional','20GRBLDOTH','Rosehip','Blend','Other',null,'Conventional','KG','No Sales'),
('29BLSFC-FL-LM-C','Blend Rooibos Lemon SFC','25GRBLDDM','Rooibos','Blend','Extra Fine Cut',null,'Conventional','KG','No Sales'),
('29BLSFC-FL-OR-C','Blend Rooibos Orange SFC','25GRBLDDM','Rooibos','Blend','Extra Fine Cut',null,'Conventional','KG','No Sales'),
('25BLCH-10F-60C-30W-B-C','Blend: CH-10F-60C-30W-B','25GRBLDDM','Rooibos','Blend','Choice Cut',null,'Conventional','KG','No Sales'),
('25BLCH-50C-50W-B-C','Blend: CH-50C-50W-B','25GRBLDDM','Rooibos','Blend','Choice Cut',null,'Conventional','KG','No Sales'),
('25BLCH-60C-40W-B-C','Blend: CH-60C-40W-B','25GRBLDDM','Rooibos','Blend','Choice Cut',null,'Conventional','KG','No Sales'),
('25BMORG-O','Blend: Organic General','25GRBLDDM','Rooibos','Blend','Other',null,'Organic','KG','No Sales'),
('25BLCH-70C-30W-B-O','Blend: ORG-CH-70C-30W-B','25GRBLDDM','Rooibos','Blend','Choice Cut',null,'Organic','KG','No Sales'),
('25BLSC-10F-70C-20W-B-O','Blend: ORG-SC-10F-70C-20W-B','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Organic','KG','No Sales'),
('25BLSE-60F-40C-B-O','Blend: ORG-SE-60F-40C-B','25GRBLDDM','Rooibos','Blend','Fine Cut',null,'Organic','KG','No Sales'),
('25BLSE-80F-20C-A-O','Blend: ORG-SE-80F-20C-A','25GRBLDDM','Rooibos','Blend','Fine Cut',null,'Organic','KG','No Sales'),
('25BLSFC-100F-A-O','Blend: ORG-SFC-100F-A','25GRBLDDM','Rooibos','Blend','Extra Fine Cut',null,'Organic','KG','No Sales'),
('25BLSFC-KUN23-O','Blend: ORG-SFC-KUN23','25GRBLDDM','Rooibos','Blend','Extra Fine Cut',null,'Organic','KG','No Sales'),
('25BLSG-22F-67C-11W-B-RO','Blend: ORG-SG-22F-67C-11W-B','25GRBLDDM','Rooibos','Blend','Short Cut',null,'RA-Organic','KG','No Sales'),
('25BLSG-27F-73C-A-O','Blend: ORG-SG-27F-73C-A','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Organic','KG','No Sales'),
('25BLSG-27F-73C-B-O','Blend: ORG-SG-27F-73C-B','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Organic','KG','No Sales'),
('25BLSG-43F-43C-14W-O','Blend: ORG-SG-43F-43C-14W','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Organic','KG','No Sales'),
('25BLSG-NAT23-B-O','Blend: ORG-SG-NAT23-B','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Organic','KG','No Sales'),
('25BLSC-10F-70C-20W-B-C','Blend: SC-10F-70C-20W-B','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25BLSE-54F-36C-10W-B-C','Blend: SE-54F-36C-10W-B','25GRBLDDM','Rooibos','Blend','Fine Cut',null,'Conventional','KG','No Sales'),
('25BLSE-60F-40C-A-C','Blend: SE-60F-40C-A','25GRBLDDM','Rooibos','Blend','Fine Cut',null,'Conventional','KG','No Sales'),
('25BLSE-60F-40C-B-C','Blend: SE-60F-40C-B','25GRBLDDM','Rooibos','Blend','Fine Cut',null,'Conventional','KG','No Sales'),
('25BLSFC-100F-B-C','Blend: SFC-100F-B','25GRBLDDM','Rooibos','Blend','Extra Fine Cut',null,'Conventional','KG','No Sales'),
('25BLSFC30-KUN25-C','Blend: SFC30-KUN25','25GRBLDDM','Rooibos','Blend','Extra Fine Cut',null,'Conventional','KG','No Sales'),
('25BLSFC-KUN25-C','Blend: SFC-KUN25','25GRBLDDM','Rooibos','Blend','Extra Fine Cut',null,'Conventional','KG','No Sales'),
('25BLSG-JOE-C-C','Blend: SG Joekels Coarse','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25BLSG-JOE-F-C','Blend: SG Joekels Fine','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25BLSG-27F-73C-C-C','Blend: SG-27F-73C-C','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25BLSG-37F-52C-11W-B-C','Blend: SG-37F-52C-11W-BA','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25BLSG-LIP15-002-C','Blend: SG-Glen','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25BLSG-LIP15-C','Blend: SG-LIP15','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25BLSG-LIP24-03-C','Blend: SG-LIP24-3','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25BLSG-NAT23-3-C','Blend: SG-NAT23-3','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25BLSG-NAT25-3-C','Blend: SG-NAT25-3','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25BLSG-NAT25-3C2-C','Blend: SG-NAT25-3C2','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25BMSE-C','Blend: Super Export General','25GRBLDDM','Rooibos','Blend','Fine Cut',null,'Conventional','KG','No Sales'),
('25BMLC-001-C','Blended: Long Cut SG','25GRBLDDM','Rooibos','Blend','Long Cut',null,'Conventional','KG','No Sales'),
('15IGCP-BLND','Contract Processing: Blend','25GRBLDDM','Rooibos','Blend','Other',null,'Conventional','KG','No Sales'),
('25REFCH-C','Refill Material: Choice','25GRBLDDM','Rooibos','Blend','Choice Cut',null,'Conventional','KG','No Sales'),
('25REFFSE-C','Refill Material: FSE','25GRBLDDM','Rooibos','Blend','Extra Fine Cut',null,'Conventional','KG','No Sales'),
('25REFORG-O','Refill Material: ORG','25GRBLDDM','Rooibos','Blend','Other',null,'Organic','KG','No Sales'),
('25REFSE-C','Refill Material: SE','25GRBLDDM','Rooibos','Blend','Fine Cut',null,'Conventional','KG','No Sales'),
('25REFSG-C','Refill Material: SG','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('30FPBL-CH-001-C','Rooibos Blend - Chai','30GRFINGD','Rooibos','Finished','Other',null,'Conventional','KG','Active'),
('30FPBUCHU-001-C','Buchu Leaves','30GRFINGD','Botanicals','Finished','Other',null,'Conventional','KG','Active'),
('30FPBUCHU-001-O','Buchu Leaves - Organic','30GRFINGD','Botanicals','Finished','Other',null,'Organic','KG','Active'),
('30FPBUCHU-002-C','Buchu TBC','30GRFINGD','Botanicals','Finished','Other',null,'Conventional','KG','Active'),
('30FPCH-001A-O','Organic - Choice','30GRFINGD','Rooibos','Finished','Choice Cut',null,'Organic','KG','No Purchases'),
('30FPCH-001B-C','Choice','30GRFINGD','Rooibos','Finished','Choice Cut',null,'Conventional','KG','No Purchases'),
('30FPCH-001B-RC','Choice - (RA)','30GRFINGD','Rooibos','Finished','Choice Cut',null,'RA-Conventional','KG','No Purchases'),
('30FPCH-002B-C','Choice: Short Cut','30GRFINGD','Rooibos','Finished','Choice Cut',null,'Conventional','KG','No Purchases'),
('30FPCH-003B-O','Organic - Choice 100','30GRFINGD','Rooibos','Finished','Choice Cut',null,'Organic','KG','No Purchases'),
('30FPCH-004B-C','Choice 100','30GRFINGD','Rooibos','Finished','Choice Cut',null,'Conventional','KG','No Purchases'),
('30FPCH-004B-O','Organic - Choice 100','30GRFINGD','Rooibos','Finished','Choice Cut',null,'Organic','KG','No Purchases'),
('30FPCH-005B-C','Choice 100','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPCH-005B-O','Organic - Choice 100','30GRFINGD','Rooibos','Finished','Choice Cut',null,'Organic','KG','No Purchases'),
('30FPCITDRY-001-C','Dried Citrus: Orange Pieces 1/8','30GRFINGD','Botanicals','Finished','Other',null,'Conventional','KG','Active'),
('30FPCITDRY-003-C','Dried Citrus: Orange Pieces 1/4','30GRFINGD','Botanicals','Finished','Other',null,'Conventional','KG','Active'),
('30FPCSG-001A-C','Coarse Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPESP-002-C','Rooibos Espresso','30GRFINGD','Rooibos','Finished','Espresso',null,'Conventional','KG','No Purchases'),
('30FPESP-002-V-C','Rooibos Espresso','30GRFINGD','Rooibos','Finished','Espresso',null,'Conventional','KG','No Purchases'),
('30FPESP-003-LC-C','Drink: RBOS Espresso','30GRFINGD','Rooibos','Finished','Espresso',null,'Conventional','KG','No Purchases'),
('30FPESP-004-C','Rooibos Espresso','30GRFINGD','Rooibos','Finished','Espresso',null,'Conventional','KG','No Purchases'),
('30FPEX-HB-001-C','Extract - Honeybush PE100','30GRFINGD','Honeybush','Finished','Other',null,'Conventional','KG','Active'),
('30FPEX-HB-002-C','Extract - Honeybush Green PE100','30GRFINGD','Honeybush','Finished','Other',null,'Conventional','KG','Active'),
('30FPEX-RB-001-C','Extract - Rooibos','30GRFINGD','Rooibos','Finished','Espresso',null,'Conventional','KG','Active'),
('30FPFSE15-001A-RO','Organic - Super Fine Cut 15 RA','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'RA-Organic','KG','No Purchases'),
('30FPFSE15-002A-C','Fine Super Export 15','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPFSE15-002B-C','Fine Super Export 15','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPFSE15-002C-C','Fine Super Export 15','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPFSE20-001A-C','Fine Super Export 20','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPFSE20-001A-O','Organic - Fine Super Export 20','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Organic','KG','No Purchases'),
('30FPFSE20-001A-RC','Super Fine Cut Bold','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'RA-Conventional','KG','No Purchases'),
('30FPFSE20-001A-RO','Organic - Super Fine Cut 20 RA','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'RA-Organic','KG','No Purchases'),
('30FPFSE20-001B-O','Organic - Fine Super Export 20','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Organic','KG','No Purchases'),
('30FPFSE20-001B-V-O','Organic - Fine Super Export 20','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Organic','KG','No Purchases'),
('30FPFSE20-002B-C','Fine Super Export 20','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPFSE20-002B-O','Organic - Fine Super Export 20','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Organic','KG','No Purchases'),
('30FPFSE30-001A-C','Fine Super Export 30','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPFSE30-001A-RC','Super Fine Cut Bold','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'RA-Conventional','KG','No Purchases'),
('30FPFSE30-KUN25-RC','Super Fine Cut Bold - RA Conventional','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'RA-Conventional','KG','No Purchases'),
('30FPFSE35-001B-C','Fine Super Export 35','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPFSE40-001B-C','Fine Super Export 40','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPFSE40-001B-O','Organic - Fine Super Export 40','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Organic','KG','No Purchases'),
('30FPFSE40-001B-RO','Organic - Fine Super Export 40 RA','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'RA-Organic','KG','No Purchases'),
('30FPFSE40-001C-C','Fine Super Export 40','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPFSE40-002B-RC','Super Fine Cut 40 - RA Conventional','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'RA-Conventional','KG','No Purchases'),
('30FPGREEN-001-O','Organic - Green Rooibos TBC','30GRFINGD','Rooibos','Finished','Green Tea',null,'Organic','KG','Active'),
('30FPGREEN-002-O','Organic - Green Rooibos Fine Cut','30GRFINGD','Rooibos','Finished','Green Tea',null,'Organic','KG','Active'),
('30FPGREEN-003-O','Organic - Green Rooibos Long Cut','30GRFINGD','Rooibos','Finished','Green Tea',null,'Organic','KG','Active'),
('30FPGREEN-005-O','Organic - Green Rooibos Long Cut','30GRFINGD','Rooibos','Finished','Green Tea',null,'Organic','KG','Active'),
('30FPHB-001-C','Honeybush: Fine Cut','30GRFINGD','Honeybush','Finished','Fine Cut',null,'Conventional','KG','Active'),
('30FPHB-001-O','Honeybush: Coarse Cut - Organic','30GRFINGD','Honeybush','Finished','Short Cut',null,'Organic','KG','Active'),
('30FPHB-002-C','Honeybush: Coarse Cut','30GRFINGD','Honeybush','Finished','Short Cut',null,'Conventional','KG','Active'),
('30FPHB-002-O','Honeybush: Fine Cut - Organic','30GRFINGD','Honeybush','Finished','Fine Cut',null,'Organic','KG','Active'),
('30FPHB-004-O','Honeybush: Fine Cut - Organic','30GRFINGD','Honeybush','Finished','Fine Cut',null,'Organic','KG','Active'),
('30FPHB-007-C','Honeybush: Coarse Cut','30GRFINGD','Honeybush','Finished','Short Cut',null,'Conventional','KG','Active'),
('30FPLC-001-C','Long Cut','30GRFINGD','Rooibos','Finished','Long Cut',null,'Conventional','KG','Active'),
('30FPLC-001-O','Organic - Long Cut','30GRFINGD','Rooibos','Finished','Long Cut',null,'Organic','KG','Active'),
('30FPLC-001-V-C','Long Cut','30GRFINGD','Rooibos','Finished','Long Cut',null,'Conventional','KG','Active'),
('30FPLC-002-C','Super Grade Long Cut','30GRFINGD','Rooibos','Finished','Long Cut',null,'Conventional','KG','Active'),
('30FPLC-002-O','Organic - Long Cut','30GRFINGD','Rooibos','Finished','Long Cut',null,'Organic','KG','Active'),
('30FPLC-002-RO','Organic - Long Cut RA','30GRFINGD','Rooibos','Finished','Long Cut',null,'RA-Organic','KG','Active'),
('30FPLC-003-C','Long Cut (80/20)','30GRFINGD','Rooibos','Finished','Long Cut',null,'Conventional','KG','Active'),
('30FPLC-004-C','Long Cut','30GRFINGD','Rooibos','Finished','Long Cut',null,'Conventional','KG','Active'),
('30FPLC-004-RC','Long Cut - (RA)','30GRFINGD','Rooibos','Finished','Long Cut',null,'RA-Conventional','KG','Active'),
('30FPNAT23SG-002B-O','Organic - Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Organic','KG','No Purchases'),
('30FPPHYTO-001-C','Phyto Blend Bulk Packed','30GRFINGD','Rooibos','Blend','Other',null,'Conventional','KG','Active'),
('30FPPRM-001-C','Packed Coarse Leaf','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPPRM-002-C','Packed Raw Material','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPQB-001-C','Quickbrew','30GRFINGD','Rooibos','Finished','Espresso',null,'Conventional','KG','No Purchases'),
('30FPRBCON-C','Final Product: Consignment (RB)','30GRFINGD','Rooibos','Finished','Other',null,'Conventional','KG','No Purchases'),
('30FPRB-CP-002-C','Contract Processing:  Sieving and Pasteurising','30GRFINGD','Rooibos','Finished','Other',null,'Conventional','KG','No Purchases'),
('30FPRB-CP-C','Contract Processing:  Pasteurised RB Final Product','30GRFINGD','Rooibos','Finished','Other',null,'Conventional','KG','No Purchases'),
('30FPRBD-002-C','Rooibos Dust','30GRFINGD','Rooibos','Finished','Espresso',null,'Conventional','KG','No Purchases'),
('30FPRHD-001-C','Rosehip Powder','30GRFINGD','Rosehip','Finished','Other',null,'Conventional','KG','Active'),
('30FPRS-001-O','Organic - RS Rooibos','30GRFINGD','Rooibos','Finished','Short Cut',null,'Organic','KG','No Purchases'),
('30FPRSR-001-C','RS Rooibos','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSC-001A-C','Short Cut','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSC-001B-C','Short Cut','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSC-001B-O','Organic - Short Cut','30GRFINGD','Rooibos','Finished','Short Cut',null,'Organic','KG','No Purchases'),
('30FPSC-001B-V-C','Short Cut','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSC-002A-O','Organic - Short Cut','30GRFINGD','Rooibos','Finished','Short Cut',null,'Organic','KG','No Purchases'),
('30FPSC-002B-C','Short Cut 100','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSC-005C-C','Short Cut - Prison','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSE-001A-C','Super Export','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSE-001A-FO','Organic - Super Export FT','30GRFINGD','Rooibos','Finished','Fine Cut',null,'FT-Organic','KG','No Purchases'),
('30FPSE-001B-C','Super Export','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSE-001B-O','Organic - Super Export','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Organic','KG','No Purchases'),
('30FPSE-001B-RC','Super Export (RA)','30GRFINGD','Rooibos','Finished','Fine Cut',null,'RA-Conventional','KG','No Purchases'),
('30FPSE-001B-V-C','Super Export','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSE-001B-V-O','Organic - Super Export','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Organic','KG','No Purchases'),
('30FPSE100-001A-C','Super Export 100','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSE100-001A-O','Organic - Super Export 100','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Organic','KG','No Purchases'),
('30FPSE100-001A-V-C','Super Export 100','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSE100-001B-C','Super Export 100','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSE100-001B-O','Organic - Super Export 100','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Organic','KG','No Purchases'),
('30FPSE100-002B-C','Super Export 100','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSE100-002B-O','Organic - Super Export 100','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Organic','KG','No Purchases'),
('30FPSE100-002B-RC','Super Export 100 (RA)','30GRFINGD','Rooibos','Finished','Fine Cut',null,'RA-Conventional','KG','No Purchases'),
('30FPSE100-003A-O','Organic - Super Export 100','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Organic','KG','No Purchases'),
('30FPSFC-001A-C','Super Fine Cut','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSFC-001A-O','Organic - Super Fine Cut','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Organic','KG','No Purchases'),
('30FPSFC-002A-C','Super Fine Cut','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSFC-002A-O','Organic - Super Fine Cut','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Organic','KG','No Purchases'),
('30FPSFC-002B-C','Super Fine Cut','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSFC-002B-O','Organic - Super Fine Cut','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Organic','KG','No Purchases'),
('30FPSFC100-001A-O','Organic - Super Fine Cut 100','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Organic','KG','No Purchases'),
('30FPSFC100-001B-C','Super Fine Cut 100%','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSFC100-001B-O','Organic - Super Fine Cut 100','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Organic','KG','No Purchases'),
('30FPSFC100-001B-V-C','Super Fine Cut 100%','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSFC100-002B-C','Super Fine Cut 100%','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSFC-FL-LM-001-C','Rooibos Lemon SFC','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSFC-FL-OR-001-C','Rooibos Orange SFC','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSFC-KUN25-C','Super Fine Cut - Conventional','30GRFINGD','Rooibos','Finished','Extra Fine Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-001A-O','Organic - Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Organic','KG','No Purchases'),
('30FPSG-001B-O','Organic - Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Organic','KG','Active'),
('30FPSG-001B-RO','Organic - Super Grade RA','30GRFINGD','Rooibos','Finished','Short Cut',null,'RA-Organic','KG','No Purchases'),
('30FPSG-001C-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-002C-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-003B-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-003C-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-004B-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-004C-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-006B-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-009C-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-010C-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-011-B-C','Super Grade - Conventional','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-015-B-RO','Organic - Super Grade RA','30GRFINGD','Rooibos','Finished','Short Cut',null,'RA-Organic','KG','No Purchases'),
('30FPSG-EKA23-2-C','Super Grade 100','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-JOE-C-001-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-JOE-F-001-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-LIP15-002-C','Super Grade - Glen','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-LIP15-C','Super Grade - Glen','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-LIP24-3-C','Super Grade - Ruby','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-NAT23-3-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-NAT23-3-P-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-NAT23P-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-NAT25-3-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-NAT25-3C2-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPSG-NAT25-3C-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPYOGI-FSE40-001-O','Yogi Fine Super Export 40','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Organic','KG','No Purchases'),
('30FPYOGI-SG-001-RO','Yogi Super Grade - RA Organic','30GRFINGD','Rooibos','Finished','Short Cut',null,'RA-Organic','KG','No Purchases'),
('31FPESP-1000-01-C','Rooibos Espresso Packed 1kg','30GRFINGD','Rooibos','Packed','Espresso',null,'Conventional','KG','Active'),
('31FPESP-1000-02-C','Rooibos Espresso Packed 1kg ( Unbranded )','30GRFINGD','Rooibos','Packed','Espresso',null,'Conventional','KG','Active'),
('31FPSLL-0050-C','Superlative Long Leaf Rooibos 50g','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','PB50G','No Purchases'),
('31FPSLL-0150-C','Superlative Long Leaf Rooibos 150g','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','PB150G','No Purchases'),
('31FPSLL-0450-C','Superlative Long Leaf Rooibos 450g','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','PB450G','No Purchases'),
('31FPSLL-0850-C','Superlative Long Leaf Rooibos 850g','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','PB850G','No Purchases'),
('31FPSML-0075-C','Supreme Medium Leaf Rooibos 75g','30GRFINGD','Rooibos','Packed','Short Cut',null,'Conventional','PB75G','Active'),
('31FPSML-0200-C','Supreme Medium Leaf Rooibos 200g','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','PB200G','No Purchases'),
('31FPSML-0500-C','Supreme Medium Leaf Rooibos 500g','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Conventional','PB500G','No Purchases'),
('31FPSML-1000-C','Supreme Medium Leaf Rooibos 1kg','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Conventional','PB1KG','No Purchases'),
('35HMCH-C','High Moisture: Choice - Conventional','35GRWASTE','Rooibos','High Moist','Other',null,'Conventional','KG','No Sales'),
('35HMCH-O','High Moisture: Choice - Organic','35GRWASTE','Rooibos','High Moist','Other',null,'Organic','KG','No Sales'),
('35HMCH-RC','High Moisture: Choice - RA Conventional','35GRWASTE','Rooibos','High Moist','Other',null,'RA-Conventional','KG','No Sales'),
('35HMCH-RO','High Moisture: Choice - RA Organic','35GRWASTE','Rooibos','High Moist','Other',null,'RA-Organic','KG','No Sales'),
('35HMFSE-C','High Moisture: FSE - Conventional','35GRWASTE','Rooibos','High Moist','Other',null,'Conventional','KG','No Sales'),
('35HMFSE-O','High Moisture: FSE - Organic','35GRWASTE','Rooibos','High Moist','Other',null,'Organic','KG','No Sales'),
('35HMFSE-RC','High Moisture: FSE - RA Conventional','35GRWASTE','Rooibos','High Moist','Other',null,'RA-Conventional','KG','No Sales'),
('35HMFSE-RO','High Moisture: FSE - RA Organic','35GRWASTE','Rooibos','High Moist','Other',null,'RA-Organic','KG','No Sales'),
('35HMSFC-C','High Moisture: SFC - Conventional','35GRWASTE','Rooibos','High Moist','Other',null,'Conventional','KG','No Sales'),
('35HMSFC-O','High Moisture: SFC - Organic','35GRWASTE','Rooibos','High Moist','Other',null,'Organic','KG','No Sales'),
('35HMSFC-RC','High Moisture: SFC - RA Conventional','35GRWASTE','Rooibos','High Moist','Other',null,'RA-Conventional','KG','No Sales'),
('35HMSFC-RO','High Moisture: SFC - RA Organic','35GRWASTE','Rooibos','High Moist','Other',null,'RA-Organic','KG','No Sales'),
('35HMSG-C','High Moisture: SG - Conventional','35GRWASTE','Rooibos','High Moist','Other',null,'Conventional','KG','No Sales'),
('35HMSG-O','High Moisture: SG - Organic','35GRWASTE','Rooibos','High Moist','Other',null,'Organic','KG','No Sales'),
('35HMSG-RC','High Moisture: SG - RA Conventional','35GRWASTE','Rooibos','High Moist','Other',null,'RA-Conventional','KG','No Sales'),
('35HMSG-RO','High Moisture: SG - RA Organic','35GRWASTE','Rooibos','High Moist','Other',null,'RA-Organic','KG','No Sales'),
('35WGFW','Floor Waste + Wet clumps','35GRWASTE','Rosehip','Waste','Other',null,'Conventional','KG','No Purchases'),
('35WGH','Waste Hair','35GRWASTE','Rosehip','Waste','Other',null,'Conventional','KG','Active'),
('35WPWC-C','Wet clumps - Conventional','35GRWASTE','Rosehip','Waste','Other',null,'Conventional','KG','No Sales'),
('35WPW-CLEAN-C','Cleaning Waste - Conventional','35GRWASTE','Rooibos','Waste','Other',null,'Conventional','KG','No Sales'),
('35WPW-FLOOR-C','Floor Waste - Conventional','35GRWASTE','Rooibos','Waste','Other',null,'Conventional','KG','No Sales'),
('35WPW-MAG-C','Magnet Waste - Conventional','35GRWASTE','Rooibos','Waste','Other',null,'Conventional','KG','No Sales'),
('35WPW-MAIN-C','Maintenance Waste - Conventional','35GRWASTE','Rooibos','Waste','Other',null,'Conventional','KG','No Sales'),
('60FPCH','Intaba Packed - Chai','50PACKED','Rooibos','Packed','Other',null,'Conventional','PCS','Active'),
('60FPRB','Intaba Packed - Rooibos','50PACKED','Rooibos','Packed','Other',null,'Conventional','PCS','Active'),
('60POUBB','Pouches - Bush Babies','50PACKED','Rooibos','Packed','Other',null,'Conventional','PCS','Active'),
('60POUCH','Pouches - Chai','50PACKED','Rooibos','Packed','Other',null,'Conventional','PCS','Active'),
('60POUCUP','Pouches - Robusto Cuppa','50PACKED','Rooibos','Packed','Other',null,'Conventional','PCS','Active'),
('60POUHB','Pouches - Honeybush','50PACKED','Honeybush','Packed','Other',null,'Conventional','PCS','Active'),
('60POU-PHYTO-C','Pouch: Phyto Blend Tea Edws 30''s','50PACKED','Rooibos','Finished','Other',null,'Conventional','P30S','Active'),
('60POURB','Pouches - Rooibos','50PACKED','Rooibos','Packed','Other',null,'Conventional','PCS','Active'),
('60TBAGRB','Sample Tea Bags - Rooibos','50PACKED','Rooibos','Packed','Other',null,'Conventional','PCS','Active'),
('80MNT-001','HKJ 350 die, 4.5 x 45 mm / 30.0','80MNT','Maintenance','Spares','Other',null,'Conventional','PCS','No Sales'),
('80MNT-002','HKJ 350 roller shells, dimpled','80MNT','Maintenance','Spares','Other',null,'Conventional','PCS','No Sales'),
('80MNT-003','Motor: 75W','80MNT','Maintenance','Spares','Other',null,'Conventional','PCS','No Sales'),
('80MNT-999','Used in Machine','80MNT','Maintenance','Spares','Other',null,'Conventional','PCS','No Sales'),
('15HBD-C','Dust: Honeybush - Conventional','15GRINTOTH','Honeybush','Dust','Other',null,'Conventional','KG','No Sales'),
('15HBIS-C','Honeybush Indent Sticks - Conventional','15GRINTOTH','Honeybush','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGGREENBY','Green Tea Dry: By Products','15GRINTOTH','Rooibos','Other','Other',null,'Conventional','KG','No Sales'),
('35WGRD-CP','Contract Processing: Red Dust - Conventional','15GRINTOTH','Rosehip','Dust','Other',null,'Conventional','KG','No Sales'),
('35WGRD-C','Red Dust - Conventional','15GRINTOTH','Rosehip','Dust','Other',null,'Conventional','KG','No Sales'),
('35WGRD-O','Red Dust - Organic','15GRINTOTH','Rosehip','Dust','Other',null,'Organic','KG','No Sales'),
('35WGYD-C','Yellow Dust - Conventional','15GRINTOTH','Rosehip','Dust','Other',null,'Conventional','KG','No Sales'),
('35WGY-O','Yellow Dust - Organic','15GRINTOTH','Rosehip','Dust','Other',null,'Organic','KG','No Sales'),
('35RHREJECTED','RH Rejected/Old Material Items','15GRINTOTH','Rosehip','Other','Other',null,'Conventional','KG','No Sales'),
('15IG1C-C','1st Cut - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IG1C-O','1st Cut - Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Organic','KG','No Sales'),
('15IG1C-RC','1st Cut - RA Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'RA-Conventional','KG','No Sales'),
('15IG1C-RO','1st Cut - RA Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'RA-Organic','KG','No Sales'),
('15IGBL-CUT-COL-LC-C','Long Cut: Wood Cut/Colored - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGBL-CUT-LC-C','Long Cut: Wood Cut - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGBLD-C','Blocks: Dirty - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGBLD-O','Blocks: Dirty - Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Organic','KG','No Sales'),
('15IGBLD-RC','Blocks: Dirty - RA Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'RA-Conventional','KG','No Sales'),
('15IGBLD-RO','Blocks: Dirty - RA Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'RA-Organic','KG','No Sales'),
('15IGBL-LC-C','Long Cut: Wood - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGCHS-C-C','Cut Heavy Stick Coarse - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGCHS-C-O','Cut Heavy Stick Coarse - Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Organic','KG','No Sales'),
('15IGCP-BL','Contract Processing: Blocks','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGCP-IS','Contract Processing: Indent Sticks','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGCP-ST','Contract Processing: Sticks','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGIS-C','Indent Sticks - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGIS-LC-C','Long Cut: Needles - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGIS-O','Indent Sticks - Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Organic','KG','No Sales'),
('15IGIS-RC','Indent Sticks - RA Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'RA-Conventional','KG','No Sales'),
('15IGIS-RO','Indent Sticks - RA Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'RA-Organic','KG','No Sales'),
('15IGISS-LC-C','Long Cut: Needles Sieved - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGMCL-C','Mixed Coarse Leaf - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGMCL-O','Mixed Coarse Leaf - Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Organic','KG','No Sales'),
('15IGSSC-C','SS-Coarse - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGST-B-C','Blended Stick - 75IS-25ST - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGST-BC-C','Blended Sticks Cut: 75IS-25ST - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGST-BC-O','Blended Sticks Cut: 75IS-25ST - Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Organic','KG','No Sales'),
('15IGST-BCP-C','Blended Sticks Cut Pasteurised: 75IS-25ST - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGST-BCP-O','Blended Sticks Cut Pasteurised: 75IS-25ST - Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Organic','KG','No Sales'),
('15IGST-B-O','Blended Stick - 75IS-25ST - Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Organic','KG','No Sales'),
('15IGST-C','Sticks - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGST-LC-C','Long Cut: Heavy Wood - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGST-O','Sticks - Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Organic','KG','No Sales'),
('15IGST-RC','Sticks - RA Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'RA-Conventional','KG','No Sales'),
('15IGST-RO','Sticks - RA Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'RA-Organic','KG','No Sales'),
('15IGWWS-C','WW sticks','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('20BGCHS-F-C','Cut Heavy Stick Fine - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('20BGCHS-F-O','Cut Heavy Stick Fine - Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Organic','KG','No Sales'),
('20BGCHS-F-RC','Cut Heavy Stick Fine - RA Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'RA-Conventional','KG','No Sales'),
('20BGCHS-F-RO','Cut Heavy Stick Fine - RA Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'RA-Organic','KG','No Sales'),
('20BGCHS-C-C','Cut Heavy Stick Coarse - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('20BGCHS-C-O','Cut Heavy Stick Coarse- Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Organic','KG','No Sales'),
('20BGCHS-C-RC','Cut Heavy Stick Coarse - RA Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'RA-Conventional','KG','No Sales'),
('20BGCHS-C-RO','Cut Heavy Stick Coarse - RA Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'RA-Organic','KG','No Sales'),
('15IGBL-C-C','Blocks: Clean - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGBL-C-O','Blocks: Clean - Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGBL-C-RC','Blocks: Clean - RA Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('15IGBL-C-RO','Blocks: Clean - RA Organic','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('30FPAS-001-C','Final Product: Aspirated Seed','30GRFINGD','Rosehip','Finished','Seed',null,'Conventional','KG','Active'),
('30FPAS-001-O','Organic - Aspirated Seed','30GRFINGD','Rosehip','Finished','Seed',null,'Organic','KG','Active'),
('30FPASC10-001-C','Crushed Seed 10% - Conventional','30GRFINGD','Rosehip','Finished','Seed',null,'Conventional','KG','No Purchases'),
('30FPASC10-001-O','Organic - Crushed Seed 10%','30GRFINGD','Rosehip','Finished','Seed',null,'Organic','KG','No Purchases'),
('30FPGRBT-001-C','Granules - Black Tea','30GRFINGD','Black Tea','Finished','Granules',null,'Conventional','KG','Active'),
('30FPGR-CPF-001-C','Contract Processing: Granules Fine','30GRFINGD','Rooibos','Finished','Granules',null,'Conventional','KG','No Purchases'),
('30FPGR-CPSE-001-C','Contract Processing: Granules SE','30GRFINGD','Rooibos','Finished','Granules',null,'Conventional','KG','No Purchases'),
('30FPGRC-RH-001-C','Rosehip Coarse Cut Granules','30GRFINGD','Rosehip','Finished','Granules',null,'Conventional','KG','No Purchases'),
('30FPGRC-RH-001-O','Organic - Coarse Cut Granules','30GRFINGD','Rosehip','Finished','Granules',null,'Organic','KG','No Purchases'),
('30FPGREEN-001-C','Green Rooibos: Fine Cut','30GRFINGD','Rooibos','Finished','Granules',null,'Conventional','KG','Active'),
('30FPGREEN-001-V-C','Green Rooibos: Fine Cut -  Vacuum','30GRFINGD','Rooibos','Finished','Granules',null,'Conventional','KG','Active'),
('30FPGREEN-004-C','Green Rooibos: Long Cut','30GRFINGD','Rooibos','Finished','Granules',null,'Conventional','KG','Active'),
('30FPGRF-RH-001-C','Rosehip Fine Cut Granules','30GRFINGD','Rosehip','Finished','Granules',null,'Conventional','KG','Active'),
('30FPGRF-RH-001-O','Organic - Fine Cut Granules','30GRFINGD','Rosehip','Finished','Granules',null,'Organic','KG','No Purchases'),
('30FPGRG-CP-C','Contract Processing: Granules Green','30GRFINGD','Rooibos','Finished','Granules',null,'Conventional','KG','No Purchases'),
('30FPGR-SE-001-C','Granules - Super Export','30GRFINGD','Rooibos','Finished','Granules',null,'Conventional','KG','No Purchases'),
('30FPGRSE-001-O','Organic - Granules - Super Export','30GRFINGD','Rooibos','Finished','Granules',null,'Organic','KG','No Purchases'),
('30FPGR-SE-002-C','Granules - Super Export Plus','30GRFINGD','Rooibos','Finished','Granules',null,'Conventional','KG','No Purchases'),
('30FPGR-SE-004-C','Granules - Super Export','30GRFINGD','Rooibos','Finished','Granules',null,'Conventional','KG','No Purchases'),
('30FPGR-SE-004-O','Organic - Granules - Super Export','30GRFINGD','Rooibos','Finished','Granules',null,'Organic','KG','No Purchases'),
('30FPGR-SF-001-C','Granules - Super Fine','30GRFINGD','Rooibos','Finished','Granules',null,'Conventional','KG','No Purchases'),
('30FPGRSF-001-O','Organic - Granules - Super Fine','30GRFINGD','Rooibos','Finished','Granules',null,'Organic','KG','No Purchases'),
('30FPGR-SF-001-V-C','Granules - Super Fine - Vacuum','30GRFINGD','Rooibos','Finished','Granules',null,'Conventional','KG','No Purchases'),
('30FPGR-SG-001-C','Granules - Super Grade','30GRFINGD','Rooibos','Finished','Granules',null,'Conventional','KG','No Purchases'),
('30FPGRSG-001-O','Organic - Granules - Super Grade','30GRFINGD','Rooibos','Finished','Granules',null,'Organic','KG','No Purchases'),
('30FPLC-003-O','Organic - Super Grade Long Cut','30GRFINGD','Rooibos','Finished','Granules',null,'Organic','KG','No Purchases'),
('30FPPC-001-C','Final Product: Pyramid Cut','30GRFINGD','Rosehip','Finished','Shell',null,'Conventional','KG','No Purchases'),
('30FPPC-001-O','Organic - Pyramid Cut','30GRFINGD','Rosehip','Finished','Shell',null,'Organic','KG','No Purchases'),
('30FPPC10-001-C','Final Product: Pyramid Cut 10%','30GRFINGD','Rosehip','Finished','Shell',null,'Conventional','KG','No Purchases'),
('30FPPC10-001-O','Organic - Pyramid Cut 10%','30GRFINGD','Rosehip','Finished','Shell',null,'Organic','KG','No Purchases'),
('30FPPC10-002-C','Final Product: Pyramid Cut 10%','30GRFINGD','Rosehip','Finished','Shell',null,'Conventional','KG','No Purchases'),
('30FPPC10-002-O','Organic - Pyramid Cut 10%','30GRFINGD','Rosehip','Finished','Shell',null,'Organic','KG','No Purchases'),
('30FPRHD-001-O','Organic - Rosehip Powder','30GRFINGD','Rosehip','Finished','Shell',null,'Organic','KG','No Purchases'),
('30FPSH-001-C','Finished Product Shell - Conventional','30GRFINGD','Rosehip','Finished','Shell',null,'Conventional','KG','No Purchases'),
('30FPSH-001-O','Organic - Shell','30GRFINGD','Rosehip','Finished','Shell',null,'Organic','KG','Active'),
('30FPSH25-001-C','Shell 25% Blend','30GRFINGD','Rosehip','Finished','Shell',null,'Conventional','KG','No Purchases'),
('30FPSH25-001-O','Organic - Shell 25% Blend','30GRFINGD','Rosehip','Finished','Shell',null,'Organic','KG','No Purchases'),
('30FPTBC-001-C','Final Product: TBC','30GRFINGD','Rosehip','Finished',null,null,'Conventional','KG','Active'),
('30FPTBC-001-O','Organic - TBC','30GRFINGD','Rosehip','Finished',null,null,'Organic','KG','No Purchases'),
('30FPTBC10-001-C','TBC 10% Seed Blend','30GRFINGD','Rosehip','Finished',null,null,'Conventional','KG','Active'),
('30FPTBC10-001-O','Organic - TBC 10% Seed Blend','30GRFINGD','Rosehip','Finished',null,null,'Organic','KG','No Purchases'),
('30FPTBC15-001-C','TBC 15% Seed Blend','30GRFINGD','Rosehip','Finished',null,null,'Conventional','KG','No Purchases'),
('30FPTBC15-001-O','Organic - TBC 15% Seed Blend','30GRFINGD','Rosehip','Finished',null,null,'Organic','KG','No Purchases'),
('30FPTBC25-001-C','TBC 25% Seed Blend','30GRFINGD','Rosehip','Finished',null,null,'Conventional','KG','No Purchases'),
('30FPTBC25-001-O','Organic - TBC 25% Seed Blend','30GRFINGD','Rosehip','Finished',null,null,'Organic','KG','No Purchases'),
('30FPTBC40-001-C','TBC 40% Seed Blend','30GRFINGD','Rosehip','Finished',null,null,'Conventional','KG','No Purchases'),
('30FPTBC40-001-O','Organic - TBC 40% Seed Blend','30GRFINGD','Rosehip','Finished',null,null,'Organic','KG','No Purchases'),
('40SDCP-002-C','Seeds: Scarified','40TEASD','Rooibos','Seed','Other',null,'Conventional','KG','Active'),
('40SDCP-003-C','Seeds: Dirty','40TEASD','Rooibos','Seed','Other',null,'Conventional','KG','Active'),
('40SDCP-004-C','Seeds: Treated - Conventional','40TEASD','Rooibos','Seed','Other',null,'Conventional','KG','No Purchases'),
('50PPF-001','Flat Bottom Pouch: CP FB 1000 Z 1kg With Zipper','60PACKAGIN','Packaging','Pouch','Other',null,'Conventional','PIECE','No Sales'),
('15IGDBT-C','Dust: Black Tea - Conventional','15GRINTOTH','Black Tea','Dust','Other',null,'Conventional','KG','No Sales'),
('15IGAS-C','Aspirated Shell - Conventional','15GRINTOTH','Rosehip','Shell','Other',null,'Conventional','KG','No Sales'),
('15IGAS-CP','Contract Processing: Aspirated Seeds - Conventional','15GRINTOTH','Rosehip','Seed','Other',null,'Conventional','KG','No Sales'),
('15IGASD-C','Aspirated Seed - Conventional','15GRINTOTH','Rosehip','Seed','Other',null,'Conventional','KG','Active'),
('15IGASD-O','Aspirated Seed - Organic','15GRINTOTH','Rosehip','Seed','Other',null,'Organic','KG','No Sales'),
('15IGASH-CP','Contract Processing: Aspirated Shell - Conventional','15GRINTOTH','Rosehip','Shell','Other',null,'Conventional','KG','No Sales'),
('15IGAS-O','Aspirated Shell - Organic','15GRINTOTH','Rosehip','Shell','Other',null,'Organic','KG','No Sales'),
('15IGRHCC-C','Coarse: Cutter - Conventional','15GRINTOTH','Rosehip','Mix','Other',null,'Conventional','KG','No Sales'),
('15IGRHCC-O','Coarse: Cutter - Organic','15GRINTOTH','Rosehip','Mix','Other',null,'Organic','KG','No Sales'),
('15IGRHCH-C','Coarse: Hammermill - Conventional','15GRINTOTH','Rosehip','Mix','Other',null,'Conventional','KG','No Sales'),
('15IGRHCH-O','Coarse: Hammermill - Organic','15GRINTOTH','Rosehip','Mix','Other',null,'Organic','KG','No Sales'),
('15IGRHPCC-PC','Contract Processing: Coarse from PYC - Conventional','15GRINTOTH','Rosehip','Mix','Other',null,'Conventional','KG','No Sales'),
('15IGSH-C','Shell - Conventional','15GRINTOTH','Rosehip','Shell','Other',null,'Conventional','KG','No Sales'),
('15IGSH-C-C','Shell: Clean - Conventional','15GRINTOTH','Rosehip','Shell','Other',null,'Conventional','KG','No Sales'),
('15IGSH-C-O','Shell: Clean - Organic','15GRINTOTH','Rosehip','Shell','Other',null,'Organic','KG','No Sales'),
('15IGSH-CP','Contract Processing: Shell - Conventional','15GRINTOTH','Rosehip','Shell','Other',null,'Conventional','KG','No Sales'),
('15IGSH-M-C','Shell: Mixed - Conventional','15GRINTOTH','Rosehip','Mix','Other',null,'Conventional','KG','No Sales'),
('15IGSH-M-O','Shell: Mixed - Organic','15GRINTOTH','Rosehip','Mix','Other',null,'Organic','KG','No Sales'),
('15IGSH-O','Shell - Organic','15GRINTOTH','Rosehip','Shell','Other',null,'Organic','KG','No Sales'),
('15IGSSM-CP','Contract Processing: Seed and Shell Mix - Conventional','15GRINTOTH','Rosehip','Mix','Other',null,'Conventional','KG','No Sales'),
('50PAK-101','Tea Printed Pouches - Flat Bottom 150g','60PACKAGIN','Packaging','Pouch','Other',null,'Conventional','PCS','No Sales'),
('50PAK-102','Tea Printed Pouches - Flat Bottom 250g','60PACKAGIN','Packaging','Pouch','Other',null,'Conventional','PCS','No Sales'),
('50PAK-103','Tea Printed Pouches - Flat Bottom 500g','60PACKAGIN','Packaging','Pouch','Other',null,'Conventional','PCS','No Sales'),
('50PAK-104','Tea Printed Pouches - Flat Bottom 1kg','60PACKAGIN','Packaging','Pouch','Other',null,'Conventional','PCS','No Sales'),
('50PBB-001','Bag: Bulk - NBL Green (New)','60PACKAGIN','Packaging','Bag','Other',null,'Conventional','PCS','No Sales'),
('50PBB-002','Bag: Bulk - NBL Green (Returned)','60PACKAGIN','Packaging','Bag','Other',null,'Conventional','PCS','No Sales'),
('50PBB-003','Bag: Bulk - NBL Green (Second Use)','60PACKAGIN','Packaging','Bag','Other',null,'Conventional','PCS','No Sales'),
('50PBB-004','Bag: Bulk - RM Conv','60PACKAGIN','Packaging','Bag','Other',null,'Conventional','PCS','No Sales'),
('50PBB-005','Bag: Bulk - RM Org','60PACKAGIN','Packaging','Bag','Other',null,'Organic','PCS','No Sales'),
('50PBP-001','Bag: Paper Brown Craft','60PACKAGIN','Packaging','Bag','Other',null,'Conventional','PCS','No Sales'),
('50PBPP-001','Bag: Polyprop White','60PACKAGIN','Packaging','Bag','Other',null,'Conventional','PCS','No Sales'),
('50PBV-001','Bag: Quad Seal Vacuum','60PACKAGIN','Packaging','Bag','Other',null,'Conventional','PCS','No Sales'),
('50PBX-002','Carton Box: 75G/200G Pouch RSC KOC','60PACKAGIN','Packaging','Box','Other',null,'Conventional','PCS','No Sales'),
('50PBX-003','Carton Box: DWB Printed - Conventional','60PACKAGIN','Packaging','Box','Other',null,'Conventional','PCS','No Sales'),
('50PBX-004','Carton Box: DWB Printed - Organic','60PACKAGIN','Packaging','Box','Other',null,'Organic','PCS','No Sales'),
('50PBX-005','Carton Box: DWB Unprinted','60PACKAGIN','Packaging','Box','Other',null,'Conventional','PCS','No Sales'),
('50PBX-006','Carton Box: Unprinted DWB 454mm x 343mm x 344mm','60PACKAGIN','Packaging','Box','Other',null,'Conventional','PCS','No Sales'),
('50PBX-007','Carton Box:: 500G/1KG Pouch RSC KOC','60PACKAGIN','Packaging','Box','Other',null,'Conventional','PCS','No Sales'),
('50PINT-001','Intaba Packaging - Rooibos','60PACKAGIN','Packaging','Box','Other',null,'Conventional','PCS','Active'),
('50PINT-002','Intaba Packaging - Masala Chai','60PACKAGIN','Packaging','Box','Other',null,'Conventional','PCS','Active'),
('50PINT-003','Intaba Packaging - Honebush','60PACKAGIN','Packaging','Box','Other',null,'Conventional','PCS','Active'),
('50PLB-001','Liner: Bag 18kg','60PACKAGIN','Packaging','Liner','Other',null,'Conventional','PCS','No Sales'),
('50PLB-002','Liner: Bin 500kg','60PACKAGIN','Packaging','Liner','Other',null,'Conventional','PCS','No Sales'),
('50PPAL-001','Pallet: Sheet','60PACKAGIN','Packaging','Pallet','Other',null,'Conventional','PCS','Active'),
('50PPAL-002','Pallet: Domestic','60PACKAGIN','Packaging','Pallet','Other',null,'Conventional','PCS','No Sales'),
('50PPAL-003','Pallet: Export - 1100mmx1100mm','60PACKAGIN','Packaging','Pallet','Other',null,'Conventional','PCS','No Sales'),
('50PPAL-004','Pallet: Export - 1100mmx1200mm','60PACKAGIN','Packaging','Pallet','Other',null,'Conventional','PCS','No Sales'),
('50PPAL-005','Pallet: Second Hand','60PACKAGIN','Packaging','Pallet','Other',null,'Conventional','PCS','No Sales'),
('50PPAL-006','Pallet: APL carton Pallets','60PACKAGIN','Packaging','Pallet','Other',null,'Conventional','PCS','No Sales'),
('50PPHY-001','Phyto: Display Boxes - PhytoBlend','60PACKAGIN','Packaging','Box','Other',null,'Conventional','PCS','No Sales'),
('50PPHY-002','Phyto: Shipper Boxes - PhytoMed','60PACKAGIN','Packaging','Box','Other',null,'Conventional','PCS','No Sales'),
('30FPBL-VAN-001-C','Rooibos Blend - Vanilla','30GRFINGD','Rooibos','Finished','Other',null,'Conventional','KG','Active'),
('40SDCP-001-C','Contract Processing: Seeds Raw Conventional','40TEASD','Rooibos','Seed','Other',null,'Conventional','KG','Active'),
('40SDCP-001-O','Contract Processing: Seeds Raw Organic','40TEASD','Rooibos','Seed','Other',null,'Conventional','KG','Active'),
('S10LGD-C','Sieved  Leaf Domestic - Conventional','10GRLEAF','Rooibos','Leaf','Other',null,'Conventional','KG','No Sales'),
('S10LGD-O','Sieved  Leaf Domestic - Organic','10GRLEAF','Rooibos','Leaf','Other',null,'Organic','KG','No Sales'),
('S10LGD-RC','Sieved  Leaf Domestic - RA Conventional','10GRLEAF','Rooibos','Leaf','Other',null,'RA-Conventional','KG','No Sales'),
('S10LGD-RO','Sieved  Leaf Domestic - RA Organic','10GRLEAF','Rooibos','Leaf','Other',null,'RA-Organic','KG','No Sales'),
('S10LGE-C','Sieved  Leaf: Export - Conventional','10GRLEAF','Rooibos','Leaf','Other',null,'Conventional','KG','No Sales'),
('S10LGE-O','Sieved  Leaf: Export - Organic','10GRLEAF','Rooibos','Leaf','Other',null,'Organic','KG','No Sales'),
('S10LGE-RC','Sieved  Leaf: Export - RA Conventional','10GRLEAF','Rooibos','Leaf','Other',null,'RA-Conventional','KG','No Sales'),
('S10LGE-RO','Sieved  Leaf: Export - RA Organic','10GRLEAF','Rooibos','Leaf','Other',null,'RA-Organic','KG','No Sales'),
('S10LGBL-C','Sieved  Leaf: Export Blend - Conventional','10GRLEAF','Rooibos','Leaf','Other',null,'Conventional','KG','No Sales'),
('S10LGBL-O','Sieved  Leaf: Export Blend - Organic','10GRLEAF','Rooibos','Leaf','Other',null,'Organic','KG','No Sales'),
('S10LGBL-RC','Sieved  Leaf: Export Blend - RA Conventional','10GRLEAF','Rooibos','Leaf','Other',null,'RA-Conventional','KG','No Sales'),
('S10LGBL-RO','Sieved  Leaf: Export Blend - RA Organic','10GRLEAF','Rooibos','Leaf','Other',null,'RA-Organic','KG','No Sales'),
('10LGCFL-COL-RO','Cutter Fine Leaf (Coloured) - RA Organic','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'RA-Organic','KG','No Sales'),
('10LGCFL-RO','Cutter Fine Leaf - RA Organic','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'RA-Organic','KG','No Sales'),
('10LGEF-PAS-O','Sieved Fine Leaf: Export - Pasteurised Conventional','10GRLEAF','Rooibos','Leaf','Fine Cut',null,'Organic','KG','No Sales'),
('15IGALT-RO','ALT - RA Organic','15GRINTDST','Rooibos','Dust','Other',null,'RA-Organic','KG','No Sales'),
('20BGDFC-C','DFC - Conventional','15GRINTSTK','Rooibos','Sticks','Other',null,'Conventional','KG','No Sales'),
('25BLSC-30F-70C-B-O','Blend: ORG-SC-30F-70C-B','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Organic','KG','No Sales'),
('25BLSFC-100F-B-O','Blend: ORG SFC-100F-B','25GRBLDDM','Rooibos','Blend','Extra Fine Cut',null,'Organic','KG','No Sales'),
('25BLSFC-KUN23-RO','Blend: SFC-KUN23-ORG/RA','25GRBLDDM','Rooibos','Blend','Extra Fine Cut',null,'RA-Organic','KG','No Sales'),
('25BLSG-NAT25-4-C','Blend: SG-NAT25-4','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25BMSE-RO','Blend: Super Export General RA-Organic','25GRBLDDM','Rooibos','Blend','Fine Cut',null,'RA-Organic','KG','No Sales'),
('25BMSG-C','Blend: Super Grade General Conventional','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('25REFFSE-RC','Refill Material: FSE RA Conventional','25GRBLDDM','Rooibos','Blend','Extra Fine Cut',null,'RA-Conventional','KG','No Sales'),
('25REFORG-RO','Refill Material: RA-ORG','25GRBLDDM','Rooibos','Blend','Other',null,'RA-Organic','KG','No Sales'),
('30FPGR-SE-002-RC','Granules - Super Export Plus RA Conventional','30GRFINGD','Rooibos','Finished','Granules',null,'RA-Conventional','KG','No Purchases'),
('30FPSC-002B-O','Short Cut 100 - Organic','30GRFINGD','Rooibos','Finished','Short Cut',null,'Organic','KG','No Purchases'),
('30FPSE-001B-RO','Organic - Super Export RA','30GRFINGD','Rooibos','Finished','Fine Cut',null,'RA-Organic','KG','No Purchases'),
('30FPSG-004C-RC','Super Grade RA Conventional','30GRFINGD','Rooibos','Finished','Short Cut',null,'RA-Conventional','KG','No Purchases'),
('30FPSG-NAT25-4-C','Super Grade','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPTW-C','Rooibos Wood Toasted','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','Active'),
('50PBS-001','Bag: Small - RM Conv','60PACKAGIN','Packaging','Bag','Other',null,'Conventional','PCS','Active'),
('01CP-RMD-RC','Contract Processing: Raw Material Dry - RA Conventional','01CPRAWMDR','Rooibos','Raw Dry','Other',null,'Conventional','KG','No Purchases'),
('01CP-RMG-RC','Contract Processing: Raw Material Wet Green - RA Conventional','01CPRAWMWE','Rooibos','Raw Wet','Other',null,'Conventional','KG','No Sales'),
('05CONBL-C','RM Consignment: Export Blend Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Export Blend','Conventional','KG','No Sales'),
('05COND-C','RM Consignment: Domestic Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Domestic','Conventional','KG','No Sales'),
('05CONE-C','RM Consignment: Export Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Export','Conventional','KG','No Sales'),
('05CONBL-O','RM Consignment: Export Blend Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Export Blend','Organic','KG','No Sales'),
('05COND-O','RM Consignment: Domestic Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Domestic','Organic','KG','No Sales'),
('05CONE-O','RM Consignment: Export Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Export','Organic','KG','No Sales'),
('05CONBL-RC','RM Consignment: Export Blend RA-Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Export Blend','RA-Conventional','KG','No Sales'),
('05COND-RC','RM Consignment: Domestic RA-Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Domestic','RA-Conventional','KG','No Sales'),
('05CONE-RC','RM Consignment: Export RA-Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Export','RA-Conventional','KG','No Sales'),
('05CONBL-RO','RM Consignment: Export Blend RA-Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Export Blend','RA-Organic','KG','No Sales'),
('05COND-RO','RM Consignment: Domestic RA-Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Domestic','RA-Organic','KG','No Sales'),
('05CONE-RO','RM Consignment: Export RA-Organic','05RAWMDRY','Rooibos','Raw Dry','Other','Export','RA-Organic','KG','No Sales'),
('28BLSFC-KUN-001-C','Pasteurised Blend: SFC-KUN','25GRBLDDM','Rooibos','Blend','Other',null,'Conventional','KG','Active'),
('SSTKADJGFW','Stock Adjustment Items  - GFW Depot','05RAWMDRY',null,null,null,null,null,'KG','Active'),
('25BLSG-14F-57C-29W-B-C','Blend: SG 14F-57C-29W-B Conventional','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','Active'),
('25BLSE-54F-36C-10W-B-O','Blend: SE-54F-36C-10W-B - Organic','25GRBLDDM','Rooibos','Blend','Fine Cut',null,'Organic','KG','Active'),
('30FPSE100-004B-O','Super Export 100 - Organic','30GRFINGD','Rooibos','Finished','Fine Cut',null,'Organic','KG','Active'),
('25BLSE-40F-60C-B-O','Blend: SE-40F-60C-B  -  Organic','25GRBLDDM','Rooibos','Blend','Fine Cut',null,'Organic','KG','Active'),
('30FPGR-CPSE-001-O','Contract Processing: Granules SE - Organic','30GRFINGD','Rooibos','Finished','Granules',null,'Organic','KG','No Purchases'),
('25BLSG-NAT26-C','Blend: SG-NAT26 Conventional','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('30FPSG-NAT26-C','Super Grade Conventional','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('SSTKADJBH','Stock Adjustment Items  - BH Depot','05RAWMDRY',null,null,null,null,null,'KG','Active'),
('SSTKADJVRD','Stock Adjustment Items  - VRD Depot','05RAWMDRY',null,null,null,null,null,'KG','Active'),
('31FPESP-1000-01-O','Rooibos Espresso Packed 1kg - Organic','30GRFINGD','Rooibos','Packed','Espresso',null,'Organic','KG','Active'),
('31FPESP-0100-01-O','Rooibos Espresso Packed 100gr - Organic','30GRFINGD','Rooibos','Packed','Espresso',null,'Organic','PB100G','Active'),
('31FPESP-0400-01-O','Rooibos Espresso Packed 400gr - Organic','30GRFINGD','Rooibos','Packed','Espresso',null,'Organic','PB400G','Active'),
('25BLMILTH-TBC-001-C','Phyto: Milk Thistle Tea Cut - Conventional','20GRBLDOTH','Botanicals','Blend','Other',null,'Conventional','KG','No Sales'),
('30FPTBC20-001-C','TBC 20% Seed Blend','30GRFINGD','Rosehip','Finished','Other',null,'Conventional','KG','No Purchases'),
('30FPCL-001-O','Pure Leaf - Organic','30GRFINGD','Rooibos','Finished','Short Cut',null,'Organic','KG','Active'),
('25BL-100C-A-O','Blend: CL-100C-A Organic','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Organic','KG','Active'),
('30FPGEN-SAMPLE-C','Finished Good: Generic Sample Item - Conventional','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('30FPESP-004-O','Rooibos Espresso - Organic','30GRFINGD','Rooibos','Finished','Espresso',null,'Organic','KG','No Purchases'),
('30FPSG-NAT26-EX-C','Super Grade Conventional','30GRFINGD','Rooibos','Finished','Short Cut',null,'Conventional','KG','No Purchases'),
('25BLSG-NAT26-EX-C','Blend: SG-NAT26 Export -  Conventional','25GRBLDDM','Rooibos','Blend','Short Cut',null,'Conventional','KG','No Sales'),
('05CONE-FC','RM Consignment: Export Fairtrade Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Export','FT-Conventional','KG','No Sales'),
('05CONBL-FC','RM Consignment: Export Blend Fairtrade Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Export Blend','FT-Conventional','KG','No Sales'),
('05RMDBL-FC','Raw Material Dry: Export Blend Fairtrade Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Export Blend','FT-Conventional','KG','No Sales'),
('05RMDE-FC','Raw Material Dry: Export Fairtrade Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Export','FT-Conventional','KG','No Sales'),
('05COND-FC','RM Consignment: Domestic Fairtrade Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Domestic','FT-Conventional','KG','No Sales'),
('05CONREJ-FC','RM Consignment: Rejected Fairtrade Conventional','05RAWMDRY','Rooibos','Raw Dry','Other','Rejected','FT-Conventional','KG','No Sales'),
('30FPSE100-001A-FO','Super Export 100 - Fairtrade Organic','30GRFINGD','Rooibos','Finished','Fine Cut',null,'FT-Organic','KG','No Purchases')
ON CONFLICT (inventory_id) DO UPDATE SET
  description=EXCLUDED.description, item_class=EXCLUDED.item_class,
  category_code=EXCLUDED.category_code, product_group=EXCLUDED.product_group,
  grade=EXCLUDED.grade, qc_grade=EXCLUDED.qc_grade, variant=EXCLUDED.variant,
  base_unit=EXCLUDED.base_unit, item_status=EXCLUDED.item_status;
