-- 20260717_004_coa_generated.sql
-- Log of generated COAs — one row per Export/generate action, with a JSON
-- snapshot of the certificate at that moment so it can be reviewed later.

CREATE TABLE IF NOT EXISTS qms.coa_generated (
  id           bigint generated by default as identity primary key,
  batch_no     text not null,
  customer     text,
  grade        text,
  variant      text,
  doc_no       text,
  generated_by text,
  generated_at timestamptz not null default now(),
  snapshot     jsonb
);

CREATE INDEX IF NOT EXISTS coa_generated_batch_idx ON qms.coa_generated (batch_no);
CREATE INDEX IF NOT EXISTS coa_generated_at_idx ON qms.coa_generated (generated_at desc);

GRANT SELECT ON qms.coa_generated TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON qms.coa_generated TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON qms.coa_generated TO service_role;
GRANT USAGE, SELECT ON SEQUENCE qms.coa_generated_id_seq TO authenticated, service_role;

COMMENT ON TABLE qms.coa_generated IS 'Log of generated COAs — one row per Export/generate, with a snapshot of the certificate at that time.';
