-- 20260717_003_coa_specs.sql
-- Per-customer COA specification matrix (imported from Client_Specs.xlsx).
--
-- One row per customer product spec (doc_no, e.g. "IPS-ACO-001"). Drives the
-- COA Generator: which analyses each customer's certificate requires, and the
-- exact spec value for each. A field value of the literal string
-- 'NOT REQUIRED' means that analysis/mesh is NOT on that customer's COA.
--
-- Identity + physical fields are columns; the many analysis fields (mesh, micro,
-- contaminants, other) live in specs jsonb so analyses can be added without a
-- schema change. Shape:
--   specs.mesh.{">6",">8",...} = { spec, min, max }
--   specs.micro.{tpc,ecoli,salmonella,yeast,mould,listeria,...}
--   specs.contaminants.{lead,cadmium,mercury,arsenic,copper,pyrrolizidine_alkaloids,...}
--   specs.other.{residue_reg,foreign_material,sensorial}

CREATE TABLE IF NOT EXISTS qms.coa_specs (
  id                  bigint generated by default as identity primary key,
  doc_no              text unique not null,
  type                text,
  customer            text,
  product_description text,
  grade               text,
  variant             text,
  moisture_max        text,
  bd_min              text,
  bd_max              text,
  specs               jsonb not null default '{}'::jsonb,
  source_file         text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

CREATE INDEX IF NOT EXISTS coa_specs_customer_idx ON qms.coa_specs (customer);
CREATE INDEX IF NOT EXISTS coa_specs_grade_variant_idx ON qms.coa_specs (grade, variant);

COMMENT ON TABLE qms.coa_specs IS 'Per-customer COA specification matrix — what each customer certificate requires and the exact spec values. Value "NOT REQUIRED" = analysis not on that customer''s COA. Imported from Client_Specs.xlsx.';
