-- ============================================================
-- AXIS — Intelligence Hub: categorization columns + run-log table
-- Run in: Supabase SQL Editor (staging first, then production).
-- ============================================================
-- Supports the AXIS dashboard's "Intelligence Hub" radial visualization —
-- a business-function x capability-layer view of change_logs entries,
-- auto-categorized by an LLM (never by hand). These columns are populated
-- by app/api/axis/categorize/run/route.ts, a background job, not the app's
-- normal write paths. No CHECK constraint on the taxonomy columns — kept as
-- free text and validated only in application code (lib/axis/hub-taxonomy.ts),
-- matching how sector/risk_level/review_status already work on this table.
-- Additive + idempotent.
-- ============================================================

ALTER TABLE axis.change_logs ADD COLUMN IF NOT EXISTS business_function   text;
ALTER TABLE axis.change_logs ADD COLUMN IF NOT EXISTS capability_layer    text;
ALTER TABLE axis.change_logs ADD COLUMN IF NOT EXISTS classify_confidence numeric;
ALTER TABLE axis.change_logs ADD COLUMN IF NOT EXISTS classify_reasoning  text;
ALTER TABLE axis.change_logs ADD COLUMN IF NOT EXISTS classify_model      text;
ALTER TABLE axis.change_logs ADD COLUMN IF NOT EXISTS categorized_at      timestamptz;

-- Selection index for "find rows needing categorization" batch queries.
CREATE INDEX IF NOT EXISTS change_logs_uncategorized_idx
  ON axis.change_logs (categorized_at) WHERE categorized_at IS NULL;

-- Aggregation index for the Hub's all-time GROUP BY cell-count query.
CREATE INDEX IF NOT EXISTS change_logs_hub_cell_idx
  ON axis.change_logs (business_function, capability_layer) WHERE business_function IS NOT NULL;

-- Run-log for the categorization background job, mirroring qms.eu_mrl_sync_log's
-- shape so failed/partial runs stay visible without checking GitHub Actions logs.
CREATE TABLE IF NOT EXISTS axis.change_log_categorization_log (
  id              bigint generated by default as identity primary key,
  started_at      timestamptz not null default now(),
  finished_at     timestamptz,
  status          text not null default 'running',
  rows_scanned    int,
  rows_classified int,
  rows_skipped    int,
  triggered_by    text,
  message         text
);
CREATE INDEX IF NOT EXISTS change_log_categorization_log_at_idx
  ON axis.change_log_categorization_log (started_at desc);

NOTIFY pgrst, 'reload schema';
